### ISSUE TITLE
Cannot convert big files in one track

### ISSUE THREAD

**Issue by ikarusnc** [audiamus/AaxAudioConverter#10]
I have two big Audiobooks (more than 900MB), I can convert them splitting by chapter but not in one track.

**Comment by xtremevicky** [comment]
Yes. I am also having this issue.

**Comment by audiamus** [comment]
I haven't tested large files, as Audible offers to download bigger audio books in parts. AAX Audio Converter has features to recombine the individual parts into a single playlist.

What might happen with very long books - but this is pure speculation - is that we run into limitations of the FFmpeg plug-in for monitoring time.

**Comment by xtremevicky** [comment]
One thing is that I am able to download that file as an "aaax" file, so the input to the application is a single file.

**Comment by audiamus** [comment]
When you navigate to your book on the Audible web page or in the Audible app, you may notice an "expand" arrow symbol. When you click it, the book will be presented in parts. Each individual part is an .aax file again, just smaller. 

It may not matter that much when converting to .m4a format, but for .mp3 the most inefficient way in AAX Audio Converter to process a book is doing it as a single file. In this case the program cannot parallelize any work and will run on one CPU core only. 

Nonetheless, I will investigate the reported issues with long or large books.

**Comment by audiamus** [comment]
This issue is directly related to #9. Duration of books longer than 24 hours is not parsed correctly due to incompatibility for time formats between FFmpeg and the .Net TimeSpan parser. Will be fixed.

As a workaround, either download a longer than 24h book in multiple parts or use one of the multiple file conversion options.

**Comment by audiamus** [comment]
Fixed in version 1.7.
