### ISSUE TITLE
support for mp3 chapter marks

### ISSUE THREAD

**Issue by akeck** [audiamus/AaxAudioConverter#104]
the mp3 format supports chapter marks.
It would be nice to add support for them if a book is converted to a single mp3 file.
Would that be possible?

**Comment by audiamus** [comment]
It's implemented. But you will need a player that can read MP3 chapter data. MPC-HC, for instance, does, but VLC does not.

**Comment by akeck** [comment]
thank you :) I'd need to find one for Android. Closing :)

**Comment by Sailfish** [comment]
akeck: fwiw, the VLC app works fine with MP3 chapter mode as long as you set the transcoding to "Multiple files by chapter".
