### ISSUE TITLE
The Windows apps are no longer available from the Audible site. They only have a download for AudibleSync now.

### ISSUE THREAD

**Issue by Redn2000** [audiamus/AaxAudioConverter#105]
I'm not sure if the activation codes can be retrieved from the AudibleSync app, but at the moment, no other versions of the Windows app are available from the Audible site or the MS Store anymore. They even have support pages saying "Note: The Audible app for Windows 10 can no longer be downloaded in the Microsoft Store." There is still a way to download and sideload the app through the [Microsoft Store Generation Project](https://store.rg-adguard.net/) along with the [app store link](https://www.microsoft.com/store/productId/9WZDNCRFJ1CR), though the viability of this method may decrease over time.

**Comment by audiamus** [comment]
That's a pity.

Now, on the other hand, I have been working on my own downloader component for a while, addressing the Audible web API  directly. The open source community has created a few implementations already, more than enough for me to delve into. The plan is to completely integrate this new component into AAX Audio Converter. However, this requires some design change for the work flow and will take more time. Therefore, I decided to temporarily host the downloader component in a standalone app, and, coincidentally, that app is just about to be released these days. So keep an eye on a new project repository here soon.

**Comment by Redn2000** [comment]
That's great to hear! Thank you for the hard work you've put into this project.

**Comment by audiamus** [comment]
So here it is, the "replacement" for the Win10 Audible app, at least from the AAX Audio Converter perspective:
https://github.com/audiamus/BookLibConnect

If you enable _Export_, you'll get pseudo .aax files and additional .json files, similar to what the Audible app produces. The json files carry the meta info for explicit chapter titles and book series title and sequence numbers. Feed this into AAX Audio Converter and it will handle this as before.

**Comment by Pel1can111** [comment]
I have just tried BookLibConnect, is there a way to get the activation code to input into AAX Audio Converter?

**Comment by audiamus** [comment]
No activation code with Book Lib Connect and no genuine AAX files. Book Lib Connect downloads files known as AAXC which come with a different and more advanced encryption. These have an individual key per book (and maybe even each download of the same book). That's why the app needs and obtains direct access to your account on the Audible server. After decryption you get M4B files, plain audio. The export function only renames them to AAX for compatibility reasons.

**Comment by Pel1can111** [comment]
oh, thanks for the quick reply. I just entered a made up activation code to enable the use of AAX Audio Converter with the AAX files exported from BookLibConnect and it seems to be working fine.

**Comment by audiamus** [comment]
I will make another and presumably final version of AAX Audio Converter generation 1, which will indicate that a dummy activation code is all you need for the pseudo AAX files you get with Book Lib Connect. And it will also inform that Book Lib Connect is available in the first place.
