### ISSUE TITLE
Where do I find my Audible activation code (8 digits) manually?

### ISSUE THREAD

**Issue by Darthagnon** [audiamus/AaxAudioConverter#11]
My computer running Windows 7 cannot install the Audible UWP app, and AudibleManager refuses to activate. Where can I find my Audible account's 8-digit code, required to run this converter? Is it on the website cookies or where?

**Comment by Darthagnon** [comment]
You don't use rainbow tables like [Pitasi's aax-to-mp3](https://github.com/Pitasi/aax-to-mp3) or [OpenAudible](https://openaudible.org/), I'm guessing.

**Comment by audiamus** [comment]
I can't really help you with Audible Manager. I suggest to contact Audible support. Nonetheless, one thing is worth to look at. If Audible Manager has successfully been associated with your account, but you cannot download any books, check your account settings on the Audible web page. There should exist a setting called "software check" or similar, telling you that it will verify you have Audible Manager installed.  This option, however, may essentially do the contrary and block any download.

**Comment by Darthagnon** [comment]
So where do I get the 8-digit Audible ID code? Do I have to phone audible and ask for it, or is there a web cookie I can look for in my browser while logged in?

**Comment by audiamus** [comment]
Audible won't give you the code.  But they should help you to get Audible Manager running. What is the problem you are encountering? The activation or the subsequent download? Once the activation has been successful, the code will be present on your machine.

BTW, Audible officially supports burning audio books to CD, via Apple iTunes, and iTunes also relies on the Audible Manager being activated.

**Comment by RoarschachMuckracken** [comment]
YOYO, I figured this issue out. You can't download Audible's sync desktop software from audible and get the authentication. you have to download This Audible Manager, then you have to update and authenticate it. THEN the convertor finds the code. Awesome software. 

https://download.cnet.com/AudibleManager/3000-2139_4-10205472.html
https://download.audible.com/audiblemanager/AM5_User_Guide.pdf

**Comment by kendrickdk** [comment]
Didn't work. It said to install the audible app (I did) but then nothing. What a waste of time.

**Comment by audiamus** [comment]
Oh dear. One of the most popular tools in this field and it won't work for you? Such a pity.

I am well aware that in this day and age no one bothers to read instructions any more, but if one would one might even spot the homepage for this project. Quote from the [Readme](https://github.com/audiamus/AaxAudioConverter/blob/master/README.md) there::
 - Requires either activated Audible App for Win10, (legacy) Audible Manager, or personal activation code.
   - _It appears that the Win10 Audible app is no longer available. You may want to try the new [Book Lib Connect downloader](https://github.com/audiamus/BookLibConnect) which is to become an integrated component of AAX Audio Converter in the future._
   - _An activation code is not needed for books downloaded with Book Lib Connect. If AAX Audio Converter asks for one, any code will do._

**Comment by Drinfeld** [comment]
Anyone knows where one can get the Audible app for windows now that has been removed from Windows store?

**Comment by audiamus** [comment]
Haven't seen any alternative source. As said above, you can try my new [Book Lib Connect](https://github.com/audiamus/BookLibConnect) downloader. With Book Lib Connect exports, any activation code will do, e.g. 12345678.

**Comment by Drinfeld** [comment]
Thank you @audiamus . Your tool works for *.aaxc files too? My problem is that my audiobooks are all in my phone as *.aaxc, and without the Windows app I can't get them in *.aax format

**Comment by audiamus** [comment]
Book Lib Connect actually downloads .aaxc format. However, with .aaxc, encryption keys are different. They are specific per book and per device. An .aaxc file on you iPhone can only be decrypted on that particular iPhone. Book Lib Connect emulates an iPhone and will register it with your Amazon account. Then, using the Audible Web API, downloads your book and the individual keys and decrypts it. Internal encryption is still standard AES, the same as with classic .aax, Book Lib Connect produces plain .m4b, but also offers to export (basically rename) to .aax, along with extracting the same meta data that the Audible Win 10 app provided. Together, that allows you to run AAX Audio Converter with all its may options.

**Comment by Drinfeld** [comment]
Thank you. I started using BLC, some books downloaded fine but others have a red slash on the status icon. What does that means?

**Comment by audiamus** [comment]
If that status is persistent, the library window will tell more. Select a single book with that status. Its meta data, description and cover image will be shown in the bottom pane. The leftmost group with the meta data will have the status as text in the top row.

Book Lib Connect also writes log files and saves the server responses as temporary files for further investigation.

**Comment by DGrv** [comment]
You can use [Audible-activator from inAudible](https://github.com/inAudible-NG/audible-activator). At the end of the procedure you will get your "activation_bytes", then copy paste in AaxAudioConverter.

I agree that for novice it may be difficult to do.
To make it simple follow the instructions, this is meaning:

- clone the repository fron Audible-activator
- Check your Chrome version (settings, about chrome)
- Download your chrome_driver ([here](https://sites.google.com/chromium.org/driver/?pli=1))  depending on your version and put it in the folder of the Audible-activator
- Install python (ecosia will help you)
- install `requests` and `selenium` via `pip install --user requests` and `pip install --user requests` via a command prompt
- Open cmd (command prompt) in the audible-activator folder
- run `audible-activator.py` and follow the instruction (login and pass ...)
- copy the "activation_bytes"
- use it in AaxAudioConverter

**Comment by audiamus** [comment]
> You can use Audible-activator from inAudible

I believe [Book Lib Connect](https://github.com/audiamus/BookLibConnect) is much easier.

**Comment by manakill** [comment]
Just found this tool after reading this thread and moving on. Drop file, get bytes, couldn't be easier! https://audible-converter.ml

**Comment by sd2812** [comment]
> My computer running Windows 7 cannot install the Audible UWP app, and AudibleManager refuses to activate. Where can I find my Audible account's 8-digit code, required to run this converter? Is it on the website cookies or where?

You can get code from here after selecting audible .aax file and use that code to convert on AAX audio Converter https://audible-converter.ml also you can convert to mp3 here.

**Comment by BrChitranjan** [comment]
This site helped me to get that code.
https://audible-tools.kamsker.at/

**Comment by LostOnTheLine** [comment]
> > You can use Audible-activator from inAudible
> 
> I believe [Book Lib Connect](https://github.com/audiamus/BookLibConnect) is much easier.

While it definitely is easier, BLC doesn't show one of my books, but I can download it from Audible's website. So for me that's a reason I need the Ativation Code for others they may have a different reason, but most people using a more complicated method aren't doing so because they think it's easier than the easy way.
