### ISSUE TITLE
Activation Code

### ISSUE THREAD

**Issue by loosenut** [audiamus/AaxAudioConverter#119]
How does one get the activation code now that the Win10 Audible app is not available?

**Comment by audiamus** [comment]
You can try [Book Lib Connect](https://github.com/audiamus/BookLibConnect), the new companion to AAX Audio Converter, to download your books directly. Book Lib Connect produces plain audio M4B files. Run AAX Audio Converter afterwards for enhanced meta data, converting to MP3, chapter splitting and more. In that case you won't need a genuine activation code. Any dummy code will do like `12345678`. 

See also #105, #109, #117, #118.

**Comment by audiamus** [comment]
There are several methods to get the activation code the proper way, from your account with Audible. InAudible is not one of them. inAudible and a few of the other older tools used a _brute force attack_ to crack the key.  As I explicitly state on my readme pages and in the manuals, my tools will never do such thing. 

I may be wrong but I guess that Audible will phase out the AAX file format altogether and concentrate on AAXC. The key for AAXC is unbreakable. That's where the Audible API clients set in, like Book Lib Connect. They download the key from Audible.
