### ISSUE TITLE
m3u playlist not working with cloudplayer 

### ISSUE THREAD

**Issue by typxxi** [audiamus/AaxAudioConverter#120]
Cloudplayer is an android app for streaming audiofiles from the cloud, in my case from onedrive.

The app is checking the whole cloudstorage for new files of type *.m3u.
Helmut Schmidt.m3u would create an audiobook in the cloudplayer app once the app has read all the mp3 files.

CURRENT ISSUE
===========

the app does not recognice any of the files contained

WORKAROUND:
===========
It took me quite a while to get behind all the issues cause I had also suffered from the Umlaut issues first like all the öäü and some other characters (not in case of audiobooks) till I found out that this app needs the m3u file in utf-8-bom format

Therefore each time I create a m3u file I also have to open the m3u file in notepad++ and do the conversion over the menu "coding - 'convert to utf-8-bom'"
Not that big deal, but I usuall do these conversions only twice a year and if I forget about the right procedure over the coding - convert menu then the tracks will be missed in the app cause there is also a menu "coding - utf-8bom"

Therefore I would love to see an option for turning utf-8-bom on.

If I do save the m3u file this way the app will recognice the new playlist and create the book / album inside the app once the first track is read and retrieved. 
Without utf-8-bom the app will not show the album.

Of cause not highest priority but would help a lot.
thx

**Comment by audiamus** [comment]
Have you tried to alter the setting for m3u playlist encoding? Not sure what the default is, but you can switch between ISO-Latin-1 and UTF-8. If that is with or without BOM I can't tell. You'll find that option in the Basic Settings, tab Conversion.

**Comment by audiamus** [comment]
I close this for now,. If you have any new findings, feel free to reopen.

**Comment by typxxi** [comment]
Quite a bit late but now I am back again.

I checked the option mentioned and saved it but had no luck.

After Upload to dropbox and accessing from cloudplayer premium / android the M3U list did not appear

Then I opened the m3u file created by adiamus with notepad+
Notepad+ showed me under CODING / KODIERUNG that it is an ansi file, not utf-8-bom. 

So I chose the conversion to utf-8-bom, saved the file, uploaded it and voila it did work.
Your current option creates an ansi and not an utf-8-bom file. 

Therefore an option as a choice between 

ANSI    - OR -   utf-8-bom

could be pretty helpfull.

**Comment by audiamus** [comment]
Thanks for the update. I'll put it on the todo list to check on the Byte Order Mark (BOM).

**Comment by audiamus** [comment]
While working on the todos for version 1.18, I checked the BOM in the playlist file, using a hex editor. It's definitely there, if the playlist is created as UTF8. That's also the default behaviour, according to the .Net Framework documentation. BOM can be explicitly switched off, but I didn't do that. So, no changes here for 1.18.
