### ISSUE TITLE
Converted audio book run time shorter then aax file run time

### ISSUE THREAD

**Issue by gearan** [audiamus/AaxAudioConverter#127]
This is my first time using this program but I noticed my audio book in aax form has a run time of 12 hours 12 minutes but the converted mps is only 11 hours 45 minutes. From what I can tell the audio itself starts and end with the same parts but I don't know why there is a near half hour difference in run time

**Comment by audiamus** [comment]
You can run AAX Audio Converter with logging switched on. I suggest to set the log level to 3 to start with. That should include the timing infos. Then zip the log file and upload it here. See the "Logging" chapter in the manual for details.

**Comment by audiamus** [comment]
I close this for the moment. Please reopen once you can provide more information.
