### ISSUE TITLE
Translation Mistakes

### ISSUE THREAD

**Issue by GeAd23** [audiamus/AaxAudioConverter#136]
There are some mistakes in the german translation. Seen in the picture.
![aax_Audio Converter Mistake](https://user-images.githubusercontent.com/39837772/169851995-9607d42f-b04a-414b-bd16-ce4c68de06f9.png)

**Comment by audiamus** [comment]
I see the word "immer" in the tooltip has typos, thank you. Anything else?

**Comment by GeAd23** [comment]
Yes Information. -> The last word. 

Yours Sincerely

**Comment by audiamus** [comment]
Oh dear. Thanks.
