### ISSUE TITLE
0 Millisekunden Problem behoben, aber  grundsätzlich Abbruch der Konvertierung

### ISSUE THREAD

**Issue by alurio** [audiamus/AaxAudioConverter#14]
Hallo !

Leider hast du das Programm zumindest bei mir zerschossen. Soll heißen, das
Kapittelnamenproblem ist behoben, aber er  bricht jetzt grundsätzlich das
Transkodieren mit der Meldung 0 Dateien konvertiert ab. Ich habe ganz
normal Auto Upgedatet, sonst nix verändert.

Gruß
Henning

**Comment by audiamus** [comment]
Erst mal keine Idee, was das sein könnte. 
Legt er denn mit dem Konvertieren los? Bewegt sich der Fortschrittsbalken?
Passiert es bei jedem Buch? Ein- und mehrteilig?
Auch im Modus "Eine Datei?
Oder mit Kapitelnamen aus?

Ich hatte ja sowie schon überlegt, ein Logging einzubauen, um Fehler einfacher einkreisen zu können. Da werde ich mich mal dransetzen.

Ansonsten ggf die 1.7 vorläufig wieder installieren und Auto-Update ausschalten, um im Moment produktiv arbeiten zu können.

**Comment by alurio** [comment]
Das Thema  kannst du schließen, die letzten Tage hat es keinerlei Probleme gegeben, keine Ahnung, was er für ein Problem hatte.

**Comment by audiamus** [comment]
OK. 

Nichtsdestoweniger baue ich das Logging ein, damit man zukünftig eine größere Chance hat, unerwartetem Verhalten auf die Schliche zu kommen.
