### ISSUE TITLE
Naming option to prevent adding [n] number tags in series book folder name

### ISSUE THREAD

**Issue by Giraffaman** [audiamus/AaxAudioConverter#140]
As far as I can see, there is not way to prevent book folder names prefixed by the volume number in square brackets, if the books are part of a series. 

I'm using [Audiobookshelf](https://www.audiobookshelf.org) and importing those folders seems to interfere with sorting over there. 
This is fixed by simply renaming the book folder into something like "book 1 - title", but it would be cool to have a naming option in AaxAudioConverter to prevent these prefixes from being added in the first place.

Other than this little thing, I just wanted to say thank you for writing and maintaining AaxAudioConverter and BookLibConnect - it's great stuff to ti be able to actually own the audiobooks I bought.

**Comment by audiamus** [comment]
Yes, some of the popular audio or multimedia library managers appear rather restricted when it comes to naming conventions. 

But as Audiobookshelf seems widely used, I will a have a look. Hopefully I can define an option that is flexible enough and also fit in the overall concept.

It will take a while, though, as I currently don't have much time for development.

**Comment by audiamus** [comment]
It's on the todo list and I'm closing this for the moment
