### ISSUE TITLE
[Feature] GNU/Linux Binaries

### ISSUE THREAD

**Issue by ncorder** [audiamus/AaxAudioConverter#155]
**Feature Request**: I would love to see the addition of GNU/Linux binaries for this application.

**Comment by audiamus** [comment]
I'm afraid I won't do that. I would have to design a new user interface from scratch, using a multi-platform GUI toolkit. And that would be based on XAML, which is far less productive than good old Windows Forms.

**Comment by avshyz** [comment]
@ncorder https://kylepiira.com/2019/05/12/how-to-break-audible-drm/
