### ISSUE TITLE
FFMpeg Transcoding Error

### ISSUE THREAD

**Issue by rieden1** [audiamus/AaxAudioConverter#160]
I've been using this app for a while to convert Audible files to MP3s to listen to in the car. So far it has been superb, but today I tried converting my latest download and it gave this FFmpeg transcoding error: 

![image](https://user-images.githubusercontent.com/93928674/206912913-a981a997-582a-4068-b181-561798631dee.png)

Is there anything I can do about this?

**Comment by rieden1** [comment]
Please ignore - it must have been a corrupted download because I downloaded it again and the new file transcoded without problems. Please keep up the good work with this excellent app!!

**Comment by audiamus** [comment]
Unfortunately, the Audible downloads don't come with checksums to validate the downloaded file.
