### ISSUE TITLE
How do i find audible code

### ISSUE THREAD

**Issue by empleat** [audiamus/AaxAudioConverter#164]
It was removed from windows store, so i can't download it, that is the thing. God amazon is so stupid, i bought their stupid book and now i can't even to listen to it without paying for some stupid converter, which i won't use for anything again anyways...

**Comment by audiamus** [comment]
The easiest thing is to re-download your book with [Book Lib Connect](https://github.com/audiamus/BookLibConnect), the companion to AAX Audio Converter. Coincidently I released the first version of it just when Audible announced to retire their Win 10 app, around a year ago. Book Lib Connect will do the decryption, so no need for an activation code.

Or you download and install legacy Audible Manager, available from CNet, I think. And people say you can still activate it. Once activated, AAX Audio Converter will find your activation code.
