### ISSUE TITLE
Drei Fehler bei den MP3 Tags seit dem letzten Update  entdeckt

### ISSUE THREAD

**Issue by alurio** [audiamus/AaxAudioConverter#166]
Hallo Audiamus, 

seit deinem letzten Update für den AAX Audioconverter auf Version 18.00 treten bei mir nach dem Download eines Buches mit Booklib Connect   und anschließender Umwandlung reproduzierbar beim Taggen der Mp3 Tags 3 Fehler auf: 
a) Kommentarfeld bleibt leer 
b) Publisher Tag wird nicht angelegt
C) Erscheinungsjahr wird unsauber eingetragen ( statt 2015 zum Beispiel 2015 01- 01

Alles  nicht tragisch, aber doch drei  Verhaltensweisen, die  es bisher nicht gab. Deshalb wollte ich sie hiermit mal reportieren.  Vielleicht lässt sich die Ursache ja finden, und  mit dem nächsten  Update beseitigen.

herzliche Grüße udn danke für die beiden Programme.

**Comment by audiamus** [comment]
Danke für den Hinweis.

Zwar hat sich in meinem Code mit 1.18 an diesen Stellen nichts geändert, wohl aber nutze ich eine neuere Version der Tag Library ATL. Und dort sind die Audible-eigenen Tags DES und PUB jetzt offensichtlich bereits in allgemeine Tags überführt worden. Werde ich auf meiner Seite anpassen.

Noch nicht nachvollziehen kann ich das Erscheinungsjahr. An allen drei Stellen im Code, die ich gefunden haben, wo dieses Datum abgerufen wird, wird nur das Jahr in Text umgewandelt.

**Comment by audiamus** [comment]
Ich habe das Thema Erscheinungsjahr weitergeleitet an den Ersteller der ATL, denn es liegt außerhalb meines Einflusses.. Es scheint so zu sein, dass das hierfür benutzte Feld "Date created" zwischenzeitlich auch andere Verwendung fand, wo ein vollständiges Datum gewollt war. Wir haben allerdings bei Audible in den Metadaten der Originaldatei weder Monat noch Tag. Damit beiderlei Nutzung möglich wird, soll die Ausbildung dieses Feldes in den ATL-Einstellungen wählbar werden. Details hier: https://github.com/Zeugma440/atldotnet/issues/182

**Comment by alurio** [comment]
Hallo Audiamus !
Na dann sind ja alle Fehler entweder schon behoben oder wird  es in Sachen Datum bald sein. 

Wirklich Klasse wie schnell gemeldete Bugs von dir angegangen werden.

**Comment by alurio** [comment]
hu

**Comment by audiamus** [comment]
1.18.1 ist jetzt veröffentlicht. 

Was wir nicht lösen konnten, ist "Publisher" bei MP4 (.m4a, .m4b). Obwohl wir der Überzeugung sind, dass ATL das richtige Tag setzt ("pub"), weigern sich alle Clients, die wir probiert haben, dieses Tag zu erkennen (https://github.com/Zeugma440/atldotnet/issues/183).
