### ISSUE TITLE
<Stück>(<Kapitel >)<nTrks>

### ISSUE THREAD

**Issue by POIZ87** [audiamus/AaxAudioConverter#167]
Eine Frage was soll bei diesem Tag passieren?
Momentan ist es so:
Stück Kapitel erzeugt:
01(Chapter 01) - Titel - Autor       [gut so] 
Stück nTrks erzeugt:
01 - Titel - Autor  
Das gleiche macht Stück ohne nTrks aber auch.
Auch bei der letzten Auswahl mit Kapitel.
<Stück>(<Kapitel >)<nTrks>
Ist das die Augabe:
01 - Titel - Autor 
Die Kapitel werden hier sogar weggelassen.

Was immer nTrks sein sollte, es klappt nicht und macht sogar die anderen Tag Ausgaben zunichte.

Bei mir hat alles was nTrks beinhaltet die gleiche Aufgabe zufolge als hätte ich nur Stück gewählt. 
(mal von Buch und Autor abgesehen.)

**Comment by audiamus** [comment]
Danke für den Hinweis. Hab das soeben noch mal nachgeschaut. Es sieht so aus, dass die drei Einträge mit "nTrks" nicht mehr ausgewertet werden. Es gibt eine weitere Option direkt darunter: "Gesamtzahl der Stücke hinzufügen". Die wird ausgewertet und macht offensichtlich das, was die drei anderen zuvor nicht tun. Dann entsteht z.B.: 
01(Chapter 01)/123 - Titel - Autor

**Comment by POIZ87** [comment]
Alles klar danke!

Vllt noch ein Wunsch, die Aufteilung nach Kapitel, lässt keine Nummerierung zu. 01 02 usw. Zumindest im Titel.
Das wäre toll, wenn eine vorangestellte Track Nummer ohne Aufspaltung der Kapitel möglich wäre.

**Comment by audiamus** [comment]
>Das wäre toll, wenn eine vorangestellte Track Nummer ohne Aufspaltung der Kapitel möglich wäre.

Die 3. Option ohne Unterordner ist nicht vorgesehen.

Was geht ist entweder die 4. Option: "Mehrere Dateien, kurze Stücke, ohne Kapitel". Dann sind die Kapitelordner weg, und die Aufspaltung danach ebenso, allerdings bleiben die Kapitel in den Metadaten drin, sowohl bei MP4 als auch bei MP3. MPC-HC z.B. kann dann immer noch kapitelweise navigieren.

Oder die 2. Option, ohne die kurzen Stücke.

Die Playlist enthält in jedem Fall die richtige Reihenfolge, auch bei Unterordnern.
