### ISSUE TITLE
Eine Datei pro AAX mit mehr als 255 Kapitel

### ISSUE THREAD

**Issue by HarveyOs** [audiamus/AaxAudioConverter#17]
Hallo audiamus

Bei 'Eine Datei pro AAX' hat die Zieldatei nur max. 255 Kapitel auch wenn die Orginal-AAX-Datei mehr hat. Das letzte Kapitel ist von der Länge her dann die Zusammenfassung der Kapitel 255-Ende.
Anbei die Kapitel-Info erzeugt mit FFmpeg -i.
Kapitel.aax.txt (Orginaldatei)
Kapitel.m4b.txt (mit AaxAudioConverter erzeugte Datei)
Kapitel.mp4.xtx (direkt durch ffmpeg umgewandelte aax-Datei)

Gruß Reinhard

[Kapitel.aax.txt](https://github.com/audiamus/AaxAudioConverter/files/4433315/Kapitel.aax.txt)
[Kapitel.m4b.txt](https://github.com/audiamus/AaxAudioConverter/files/4433316/Kapitel.m4b.txt)
[Kapitel.mp4.txt](https://github.com/audiamus/AaxAudioConverter/files/4433317/Kapitel.mp4.txt)

**Comment by audiamus** [comment]
Mir ist noch nicht klar, wo die Kapitel > 255 verloren gehen. Im Moment läuft das mit FFmpeg 4.1. Der Parameter `-map_chapters` wird bei "Eine Datei" nicht gesetzt, ist also default und sollte dann die Kapitel kopieren, lt FFmpeg Doku. (Bei allen anderen Modi steht der Parameter auf -1) 
`-activation_bytes xxxxxxxx -y -i input.aax -map_metadata -1 -vn -c:a copy output.m4a`

**Comment by HarveyOs** [comment]
Ich kann den Fehler jetzt reproduzieren.
Mit dem Aufruf
ffmpeg -activation_bytes xxxxxxxx -y -i input.aax -map_metadata _**-1**_ -vn -c:a copy output.mp4
werden maximal 255 Kapitel erzeugt.
Durch
ffmpeg -activation_bytes xxxxxxxx -y -i input.aax -map_metadata _**-0**_ -vn -c:a copy output.mp4
werden alle Kapitel kopiert

**Comment by audiamus** [comment]
Das ist nicht schön. Denn ich möchte die Tag-Metadaten aus der aax-Datei loswerden, weil sie proprietäre Tags enthalten, die ich durch Standard-Tags ersetze. Man müsste mal ausprobieren, was passiert, wenn man ´-map_metadata´ auf FFMETADATA anwendet, wie in dem FFmpeg-Beispiel:
`ffmpeg -i INPUT -i FFMETADATAFILE -map_metadata 1 -codec copy OUTPUT`
Dann könnte ich auch die AAX-Kapitel immer über FFMETADATA kopieren.

**Comment by HarveyOs** [comment]
Der Umweg über die FFMETADATA scheint zu gehen. Ich habe mal mit
ffmpeg -i INPUT -f ffmetadata FFMETADATAFILE.txt
die Meta-Daten aus der AAX geholt, artist / album_artist / comment geändert und mit
ffmpeg -activation_bytes xxxxxxxx -i INPUT -i FFMETADATAFILE.txt -map_metadata 1 -map_chapters 1 -vn -c:a copy OUTPUT
umgewandelt. Alle 378 Kapitel waren da.

**Comment by audiamus** [comment]
Super. Das ist dann der Weg, den ich verfolgen werde. 

Eine Klasse, die das FFMETADATAFILE-Format lesen und schreiben kann, habe ich heute schon mal erstellt.

**Comment by audiamus** [comment]
Ist eingebaut, Version 1.10. Habe es nur durch Manipulation im Code testen, weil ich kein Hörbuch mit so vielen Kapiteln habe. Auffällig, dass z.B. VLC trotzdem nur 255 Kapitel anzeigt, MPC-HC aber alle, FFmpeg natürlich auch. Aufpassen beim Selbst-Testen: Durch die neue Funktion "Explizite Kapitelnamen" werden die aax-Kapitel normalerweise mit denen aus der `content_meta.json` überschrieben. Option für diesen Test daher abschalten.
