### ISSUE TITLE
crash while dividing in several files

### ISSUE THREAD

**Issue by xsar69** [audiamus/AaxAudioConverter#171]
Dear developers,
I tried to convert a new aax from audible today. The file was "Die Hyänen_B0B5LQBQLR_LC_128_44100_Stereo.aax". If you need it for tests, I will send it to you.
When I selected "Mehrere Dateien, geteilt nach Kapitel" the app hangs after a few seconds.
When I tried "Eine Datei pro AAX-Datei" everthing was fine.
I hope it helps.
Best regards
xsar

**Comment by audiamus** [comment]
A log file might help. Starting with log level 3 might give us a first hint. See the manual for how to create a log.

**Comment by xsar69** [comment]
[AaxAudioConverter_2023-04-01_001.log](https://github.com/audiamus/AaxAudioConverter/files/11127402/AaxAudioConverter_2023-04-01_001.log)

**Comment by xsar69** [comment]
Sorry for the late reply!

**Comment by audiamus** [comment]
Thanks for the log. Unfortunately it doesn't reveal much other than the conversion started as expected but apparently did not finish. Now, did the app just hang or really crash with an exception message box?

- If it just hangs forever, could you raise the log level to 4? That will also log FFmpeg activity. 
- This conversion uses 32bit FFmpeg as it should. However, the 32bit FFmpeg exe is a slightly older version (the last they built) but a bit faster than later 64bit versions. You can enforce the 64bit version, though.   
Go to `C:\Program Files\audiamus\AAX Audio Converter` and open `AaxAudioConverter.exe.config` in a text editor (Admin privileges needed). Find `FFmpeg64bitHours` and change `value `from `0` to `1`. Save.

```
      <setting name="FFmpeg64bitHours" serializeAs="String">
        <value>0</value>
      </setting>
```

- If it crashes and shows the exception in a message box, could you copy the exception and the call stack and post it here? (I don't need the lengthy list of loaded assemblies that also always comes with the exception message.)
