### ISSUE TITLE
FLAC zu den Export-Formaten hinzufügen

### ISSUE THREAD

**Issue by grossmaul** [audiamus/AaxAudioConverter#173]
Hallo,
es wäre gut, wenn man beim Format auch "FLAC" auswählen kann (sofern mir Book Lib Connect überhaupt verlustfreie AAX Dateien ausgibt)

FFmpeg unterstützt auf jeden Fall FLAC.

Auf jeden Fall vielen Dank für die Mühen an diesem Projekt! Ich weiß das sehr zu schätzen!!

**Comment by audiamus** [comment]
Es gibt unzählige Audioformate. Die Beschränkung auf MP4 mit den Typen .m4b und .m4a sowie MP3 erfolgte ganz bewusst. 

- Audible-Hörbücher sind im Original seit etwa 2009 selbst MP4, mit dem AAC-Codec. Gilt sowohl für .aax als auch für .aaxc. Die Konvertierung in .m4a/.m4b ist keine, sondern "lediglich" eine Dekodierung des AAC-Audiostroms, die auf den meisten Rechnern durch die CPU hardwaremäßig unterstützt wird and daher recht flott vonstatten geht.
- MP3 wurde bis etwa 2009 von Audible verwendet, mit dem Typen .aa und intern bezeichnet als "Format 4". AAX Audio Converter kann auch .aa-Dateien lesen. Dann ist .aa zu .mp3 keine Konvertierung, sonder nur Dekodierung. 

Und eines der beiden Formate sollte nun wirklich jeder Audioplayer können. 

Welchen Zweck sollte eine Konvertierung in ein verlustfreies Audioformat erfüllen, wenn doch das Original bereits verlustbehaftet komprimiert wurde (AAC oder MP3)? Ein zuvor durch die Komprimierung entstandener theoretischer Qualitätsverlust kann ja nicht rückgängig gemacht werden. Ich schreibe bewusst "theoretischer", denn wir haben es beim Hörbuch mit menschlicher Stimme zu tun, deren Anspruch an Abtast- und Bitrate eher bescheiden ist.

**Comment by grossmaul** [comment]
Okay, danke - Ich wusste nicht, welche Formate intern verwendet werden. Ich habe oft was für FLAC im Internet gefunden, aber dass bereits intern AAC verwendet wird, wusste nicht. Da ein verlustfreier Codec da nichts besser machen kann, ist natürlich klar.

Der Fall kann dann geschlossen werden :)
