### ISSUE TITLE
IOException: [file name] issue

### ISSUE THREAD

**Issue by vkallsen** [audiamus/AaxAudioConverter#175]
Hi, I converted one aax file to m4b after adding it using the Add... button. Then I deleted the item on my list since it was already converted. I've tried to add more to convert but then I get this error message: "IOException: [file name]" and that's it. I've tried adding them through the Add...  button, drag and drop, and open with but I get nothing or the same error message. Closing and re-opening program doesn't resolve. Doesn't matter which file I pick either. Please advise, thanks!

**Comment by vkallsen** [comment]
I am using an external hard drive in case that matters?

**Comment by audiamus** [comment]
That sounds strange. This IO exception, is this a Windows message box, or an internal message by AAX Audio Converter?

- If the former, could you copy the message box text and post the call stack part here? 
- If the latter, could you run AAX Audio Converter with logging activated (see the manual, chapter 4), log level 3, and post the log here?

**Comment by vkallsen** [comment]
![image](https://user-images.githubusercontent.com/38305548/229855816-66f4851a-f8be-4326-b752-7f5a315942c0.png)

**Comment by audiamus** [comment]
OK, this happens either when reading meta data through FFmpeg or through the ATL library. Meta data must be read before AAX Audio Converter can display anything in the list. That list is never filled from the file name, always from meta data within the file. And if that fails, the list remains empty. To find out more, could you raise the log level to 4? That will also log FFmpeg output.

And is this the only .aax file causing problems? If not and all the affected files are on an external disk, can you copy one of them to a local disk and retry? It could be a disk access problem.

You can also try to run FFmpeg directly from a console window. Open console in 
`C:\Program Files\audiamus\AAX Audio Converter`
Run 
`ffmpeg.exe -hide_banner -i "F:\Audible Audiobooks\AAX Files\Dark Age_1980000174_LC_64_22050_Stereo.aax"`

**Comment by vkallsen** [comment]
[AaxAudioConverter_2023-04-04_002.log](https://github.com/audiamus/AaxAudioConverter/files/11151232/AaxAudioConverter_2023-04-04_002.log)

**Comment by vkallsen** [comment]
Happens regardless of .aax file. Happens even if I run off local disk too. I forget if I mentioned this at the top but I did convert 1 .aax file successfully before this error started happening.

**Comment by vkallsen** [comment]
I think I found the problem! It appears something happened when I exported the files to .aax with Book Lib Connect. I tried your command and got this: 
![image](https://user-images.githubusercontent.com/38305548/229871399-bca285e5-3fb6-407d-a74e-83163400419a.png)

Which made me suspicious. So I went over to look at the .aax files, and some of them are 0 KB.
![image](https://user-images.githubusercontent.com/38305548/229871535-26557fcc-0639-49b5-a091-ec5845b3e6d1.png)

Ones that are 0 KB are not working, ones that have some size to them are. Now I have to figure out how Book Lib Connect failed to export properly? Any thoughts on that or should I just delete all the 0 KB ones and try again?

**Comment by audiamus** [comment]
> It appears something happened when I exported the files

Exactly.
Line 33 in the log, same FFmpeg message:
`[FFmpeg.ffMpegAsyncHandlerAudioMeta] {#2} C:\Users\USER\Desktop\A Rare Book of Cunni_B071NDRLBK_LC_64_22050_Stereo.aax: Invalid data found when processing input`

> Ones that are 0 KB are not working, ones that have some size to them are. 

Delete those empty files and and start over with Book Lib Connect. Book Lib Connect will try to figure out what is still present and what is not. So, if you are lucky, it will not re-download the books and hereby save time. 

If empty files are created again, the Book Lib Connect log might help. Logging in Book Lib Connect is on by default, with log level  3, which should suffice.

**Comment by audiamus** [comment]
I close this for now. Please open a new issue in the [Book Lib Connect](https://github.com/audiamus/BookLibConnect/issues) section if the empty aax exports persist.
