### ISSUE TITLE
Eine Datei pro AAX mit neuen Kapitelnamen

### ISSUE THREAD

**Issue by HarveyOs** [audiamus/AaxAudioConverter#18]
Hallo audiamus

Ein Lösungsansatz für 'Eine Datei pro AAX' mit den neuen Kapitelnamen aus der *.json könnte sein wenn diese *.json vorher in das FFMETADATA-Format konvertiert wird und die *.aax dann mit
ffmpeg -activation_bytes xx-xx-xx-xx -i input.aax -i FFMETADATAFILE.txt -map_metadata 1 -map_chapters 1 -vn -c:a copy output.m4a
umgewandelt wird.

Ich habe dieses händisch mal für 'BECOMING: Meine Geschichte' probiert und die Kapitel werden in meinem SamrtAudioBook-Player richtig angezeigt.

Es ist nur eine Idee. Einige Tags (Kommentar und Titelbild z.B.) fehlen noch in der fertigen Datei.

Gruß Reinhard

[FFMETADATAFILE.txt](https://github.com/audiamus/AaxAudioConverter/files/4433523/FFMETADATAFILE.txt)

**Comment by audiamus** [comment]
Ja, das mit der separaten FFMETADATA-Datei war auch meine Idee.

Das würde aber nur die Kapitel betreffen. Die anderen Tags einschließlich Titelbild setze ich mit der TagLib.

**Comment by audiamus** [comment]
Ist implementiert. Version 1.10 enthält diese neue Funktionalität.

Noch ein Hinweis zum "langen Buchtitel". Auch die Auswahl Serie und Buch zuerst gibt es in 1.10. Aber Vorsicht, das Kriterium ist der Doppelpunkt. Enthält der Buchtitel einen Doppelpunkt auch ohne Teil einer Serie zu sein, siehe Dein Beispiel oben, würde der Parser trotzdem zuschlagen. Deshalb gibt es noch eine weitere Option in Dropdown-Liste: "Wie vorgefunden". Das entspricht der früheren Option "ja" und interpretiert den Doppelpunkt nicht.
