### ISSUE TITLE
Windows 11 ARM installer support?

### ISSUE THREAD

**Issue by sirneb** [audiamus/AaxAudioConverter#185]
For the binary installer, using Windows 11 ARM, the installer does not allow installation with the message:
```
This program can only be installed on versions of Windows designed for the following processor architectures:

x86
x64
```
Is it possible to change that restriction on the windows installer? The app as far as I know is fully functional on Windows 11 ARM. What I do right now to get around this is actually install on a separate Windows 11 x64 machine and then copy the folders to my Windows 11 ARM machine.

(Same problem with [Book Lib Connect](https://github.com/audiamus/BookLibConnect) as well, it also works just fine on my Windows 11 ARM).

By the way, thanks for the great work with these projects!

**Comment by audiamus** [comment]
I really don't know. I have no experience with Windows on ARM and no idea what might be supported and what not.

**Comment by sirneb** [comment]
I don't know much about that as well. But surprisingly, the x86/x64 to ARM translation does a great job. Most modern software just works.

**Comment by sirneb** [comment]
@tinyapps thanks for the tip, that saves me some back and forth.
