### ISSUE TITLE
M4B Menüs/Chapter fehlen

### ISSUE THREAD

**Issue by Kazaa3** [audiamus/AaxAudioConverter#19]
Die .m4b-Dateien scheinen leider keine Menüs mit den Kapitelinformationen zu enthalten:
![Menu fehlt](https://user-images.githubusercontent.com/43350149/79031164-39eaea00-7b9d-11ea-98cf-98e5528430dc.PNG)
Mit Chapter and Verse erstellte .m4b-Dateien enthalten ein Quicktime Chapter Markers Menü:
![Quicktime Chapter](https://user-images.githubusercontent.com/43350149/79031229-9c43ea80-7b9d-11ea-9b89-78b5e9c1de62.PNG)
Andere Tools schreiben sogar zwei Menüs (Quicktime & Nero Tags):
![Quicktime Chapter   Nero Tags](https://user-images.githubusercontent.com/43350149/79031434-e8dbf580-7b9e-11ea-97b5-9c8627a7f399.PNG)

**Comment by audiamus** [comment]
Interessant. Es gibt offensichtlich mehr Möglichkeiten, Kapitel in MPEG4 einzubetten, als ich bisher kannte. 

Im Modus "Eine Datei" werden bisher (in allen Versionen bis einschl 1.9) die Kapitel aus der AAX-Datei 1:1 übernommen. Das macht FFmpeg allein, AAX Audio Converter hat sich da nicht eingemischt. Wie immer die Kapitel ursprünglich im MPEG4-Container kodiert waren, so sollten sie eigentlich auch im neuen Container M4A/M4B stehen. Es scheint jetzt wohl vom auswertenden Werkzeug abzuhängen, ob man sie sieht oder nicht. 

_MediaInfo_ zeigt auch bei mir die Kapitel der von AAX Audio Converter im Modus "Eine Datei" erzeugten M4A/M4B-Dateien in der Tat nicht an. Andere, z.B. _Mp3Tag_, _MPC-HC_ oder _VLC_, tun das aber durchaus.   

Zu "Quicktime" und "Nero" habe ich vor einiger Zeit mal versucht, näheres herauszufinden, und gelesen, das erste Verfahren bette die Kapitel direkt in den Audiostrom ein, das zweite als unabhängige Metadaten. Nach meinem Verständnis nutzt AAX (MPEG4) letzteres.     

Mit der nächsten Version 1.10 kommt hier jedoch eine Änderung in AAX Audio Converter. Dann werden die Kapitel für M4A/M4B bei "Eine Datei" extern zugespielt, über eine vom Programm erzeugte FFmpeg-Meta-Datei. Das ermöglicht die Auswertung und Anwendung der `content_meta.json` aus dem Audible App-Download auch für ungeteilte M4A/M4B-Dateien. Und damit zeigt auch _MediaInfo_ die Kapitel dann an, soeben mit der 1.10-Laborversion probiert.

**Comment by audiamus** [comment]
1.10 ist nun veröffentlicht. 

Kapitelnamen sind jetzt auch in _MediaInfo_ sichtbar:

![mediainfo-chapters](https://user-images.githubusercontent.com/47717419/79044669-abab4e00-7c06-11ea-8590-2e31c467edbe.png)

Das Beispiel ist ein zweiteiliges Hörbuch, die Analyse hier ist für den zweiten Teil. Während die Original-AAX-Kapitel wieder mit Nummer 1 beginnen, wird bei den denen aus `content_meta.json` korrekt fortgesetzt. 

_(Die über mehrere Teile durchlaufende Zählung würde allerdings auch ohne_ `content_meta.json` _funktionieren, durch den seit Anfang an eingebauten Mechanismus, alle Buchteile gemeinsam verarbeiten zu können.)_

**Comment by Kazaa3** [comment]
Hey audiamus, super schneller fix. Vielen Dank.
