### ISSUE TITLE
AAX aborts during conversion

### ISSUE THREAD

**Issue by awchappell** [audiamus/AaxAudioConverter#191]
I have one book that consistently causes the program to abort.  I have done the following.

- rebooted windows
- re-downloaded the file
- rerun the conversion with different modes selected

I have attached a log file with 2 runs.   Modes "Single file per AAX file" and "Multiple files split into shorter Tracks, ignoring chapters".  I have converted over 40 books, using the  "Multiple files split into shorter Tracks, ignoring chapters", per the provided jpg, with no problems.

Thanks for the help

![aax_audio_converter_abort](https://github.com/audiamus/AaxAudioConverter/assets/125936374/1d2650d0-8acc-4ec8-b841-3b414e28080b)
[AaxAudioConverter_2023-09-20_001.zip](https://github.com/audiamus/AaxAudioConverter/files/12678667/AaxAudioConverter_2023-09-20_001.zip)

**Comment by audiamus** [comment]
According to the log file, something goes wrong while writing the meta data. I have to look it up in the code, but that will take a few days, I am currently on holidays.

**Comment by awchappell** [comment]
Enjoy your holiday.

Thanks.

**Comment by audiamus** [comment]
I have checked the source of the error message and it appears that this is related to the cover image. Could this me missing for your book?

**Comment by awchappell** [comment]
You are correct there is no cover image in the original .m4b.  I added a cover image using Mp3tag.  I then ran AAX converter and again it aborted, see attached log file.  I was converting other files and came across another file that aborted, it also did not have a cover in the .m4b.  The program does make the .mp3 files and places them in the correct folders, but no tags are filled in ie title, artist, year.
[AaxAudioConverter_2023-09-25_001.zip](https://github.com/audiamus/AaxAudioConverter/files/12719700/AaxAudioConverter_2023-09-25_001.zip)

**Comment by audiamus** [comment]
After more investigation: 

The ArgumentException "Data should not be null and be at least 3 bytes long" from ATL can only be thrown in conjunction with invalid cover image data. It seems, some sort of cover image data is present, which prevents earlier safeguards to intercept further processing, but the image data is invalid.

I will add more error checking here to let the conversion continue.

**Comment by awchappell** [comment]
If there is anything I can do to help please let me know.   If you want a
copy of the "bad" files let know.

**Comment by audiamus** [comment]
Try new version [1.18.2](https://github.com/audiamus/AaxAudioConverter/releases/tag/v1.18.2). It should no longer abort the conversion.

What actually might have gone wrong is that the book in question does have a few bytes of data for the cover image, but that data is invalid. And Mp3tag has some unexpected behavior. When adding an image, Mp3tag does not automatically remove the previous one. So the broken image may still have been there for your 2nd conversion attempt.

**Comment by awchappell** [comment]
Your update works!  The 2 problem files convert with no abort.  The .mp3 files have tags filled in and the cover is blank.  Thank you for the update.

**Comment by audiamus** [comment]
> Your update works! 

Very good.
