### ISSUE TITLE
The "MAPS" "chapter" that's included sometimes seems to be corrupt

### ISSUE THREAD

**Issue by xecrets** [audiamus/AaxAudioConverter#193]
In some books there appears a "MAPS" "chapter", that is probably not actually sound, but it's treated as such and is converted to a broken mp3 for example. It may be caused by an issue in the underlying ATL library, but I thought I'd ask first here before investigating further.

**Comment by audiamus** [comment]
Couple of questions:

1. How did you download your book? With BookLibConnect?
2. This "MAPS" chapter: Is this found in the embedded chapter meta data or in the accompanying json file?
3. Can you provide a log file? 

> Maybe there could be an additional option to simply drop silent "chapters" that last less than a given number of seconds,

AAXAudioConverter itself will add extra short silent chapters under specific conditions: If the json chapters are in a hierarchical structure, the higher layer title gets a chapter of its own, just to display the title in the player.

**Comment by xecrets** [comment]
> 1. How did you download your book? With BookLibConnect?

Both BookLibConnect and via Audible web download. Same result. It's a regular chapter apparently.
> 2. This "MAPS" chapter: Is this found in the embedded chapter meta data or in the accompanying json file?

Not quite sure what you mean here... It appears in the JSON file, and when I debug the ATL code it appears as a normal chapter there, just very short... Here is the beginning of the JSON from the BookLibConnect export:
```
{
    "content_metadata": {
        "chapter_info": {
            "brandIntroDurationMs": 1904,
            "brandOutroDurationMs": 4969,
            "chapters": [
                {
                    "length_ms": 107735,
                    "start_offset_ms": 0,
                    "start_offset_sec": 0,
                    "title": "Opening Credits"
                },
                {
                    "length_ms": 100,
                    "start_offset_ms": 107735,
                    "start_offset_sec": 107,
                    "title": "MAPS"
                },
```


It looks just like a normal chapter. But so short some players and analyzers then treat it as broken.
> 3. Can you provide a log file?

Sure, how, from what part of the process?

> AAXAudioConverter itself will add extra short silent chapters under specific conditions: If the json chapters are in a hierarchical structure, the higher layer title gets a chapter of its own, just to display the title in the player.

Yes, but this does not appear to be the case here.

**Comment by audiamus** [comment]
>  Can you provide a log file?
Sure, how, from what part of the process?

From the early stages when AaxAudioConverter is still gathering meta data. The log should tell us how that "MAPS" chapter looks in the embedded data. Log level 3 should suffice, I think. But as you get the same result with downloading the .aax file, there'll be probably no difference.

> AAXAudioConverter itself will add extra short silent chapters under specific conditions

Those extra chapters will be very much the same as your "MAPS" thing and may also confuse players. I believe these are 100ms as well. However, no one until now has reported any problem here.

What I could do is to add a "black list" with an entry "MAPS" here, but again, it somehow contradicts the extra chapter mechanism.

**Comment by xecrets** [comment]
> From the early stages when AaxAudioConverter is still gathering meta data. The log should tell us how that "MAPS" chapter looks in the embedded data. Log level 3 should suffice, I think.

Ok, I have a log file, but the full file contains a lot of information that I don't feel is appropriate for public consumption here. Can you suggest a more private channel where I can send it? Here's an extract, but I'm not sure it tells you anything relevant:

```
09:53:33.510 0001 Level=3
09:53:33.812 0001 [MainForm..ctor] AaxAudioConverter 1.18.2.0 as 64bit process on Windows 10.0.22621 64bit
09:53:33.839 0001 [ActivationCode.init] add from app (#=1)
09:53:33.839 0001 [ActivationCode.init] #unique=1
...
10:03:14.284 0005 [AaxAudioConverter.verifyActivationAndGetChapters] aax/aa chapters:
  00:00:00.000 -> 00:01:47.735 (00:01:47.735) [000000.000 000107.735]: "Opening Credits"
  00:01:47.735 -> 00:01:47.835 (00:00:00.100) [000107.735 000107.835]: "MAPS"
  00:01:47.835 -> 01:02:29.945 (01:00:42.110) [000107.835 003749.945]: "PROLOGUE"
...
10:03:14.604 0005 [AudibleAppContentMetadata.getContentMetaChapters] chapters: #zero=0, #white=0
10:03:14.605 0005 [AudibleAppContentMetadata.getContentMetaChapters] content meta chapters:
  00:00:00.000 -> 00:01:47.735 (00:01:47.735): "Opening Credits"
  00:01:47.735 -> 00:01:47.835 (00:00:00.100): "MAPS"
  00:01:47.835 -> 01:02:29.945 (01:00:42.110): "PROLOGUE"
...
10:03:14.645 0005 [AaxAudioConverter.adjustNamedChapters] Alter first: 00:00:00.000 -> 00:01:47.735 (00:01:47.735): "Opening Credits", 00:00:01.904 ->
...
10:06:07.419 0005 [TagAndFileNamingHelper.writeChapters] "(02) MAPS.mp3": #chapters=1
10:06:07.419 0005 [TagAndFileNamingHelper.writeChapters] 00:00:00.000 -> 00:00:00.100 (00:00:00.100): "MAPS"
10:06:07.460 0005 [AaxAudioConverter.updateTags] succ=True, track="MAPS" "(02) MAPS.mp3"
...
```

> What I could do is to add a "black list" with an entry "MAPS" here, but again, it somehow contradicts the extra chapter mechanism.

No, that doesn't seem the right way to go. But exclusion of short silent chapters from the source could work, you could still inject those extra chapters as needed.

**Comment by audiamus** [comment]
Thanks. So, same in the embedded chapters.

But you see the contradiction: Suppressing silent short chapters on one side, but adding them intentionally for displaying hierarchical chapter titles on the other side doesn't make any sense. The only way would be a settable option, none or all, I guess. I'll put it onto the todo list.
