### ISSUE TITLE
Numbers being prepended to file name

### ISSUE THREAD

**Issue by OscarTheDonny** [audiamus/AaxAudioConverter#197]
For some reason for this book specifically numbers are being prepended to the file name.
In the windows media overlay it shows the file name and it irks me. I have tried every setting and have not found anything.

Here is how I would like it to be:
![image](https://github.com/audiamus/AaxAudioConverter/assets/117408214/031edb23-4dfa-4178-a90f-4466ad86af8f)

Yet it shows:
![image](https://github.com/audiamus/AaxAudioConverter/assets/117408214/a6ec56aa-e8ed-48f0-b8a4-a728e07a95f6)

**Comment by OscarTheDonny** [comment]
Nevermind, it was due to the fact that there were two chapters with the name "Introduction" (ofc).
I bulk renamed the m4b files to remove the first 5 characters and then renamed one of the "Introduction.m4b"'s to "Introductions.m4b", then edited the m3u in notepad to reflect the filename changes and it all works well now, sorry for the bother.

**Comment by audiamus** [comment]
Yes, this is the intended behaviour if the selected file name pattern produces duplicate names.
