### ISSUE TITLE
Is it possible to split to MP3 by narrator?

### ISSUE THREAD

**Issue by YukihimeX** [audiamus/AaxAudioConverter#198]
So is  it possible to split the book into different tracks based on the Narrator? Just like the mode that split book into Chapter but I want it in Narrator instead. 
If not then please allow the naming convention to include Narrator in it?

**Comment by audiamus** [comment]
It's not possible, I'm afraid. Audible doesn't provide per-chapter meta data. The only thing you may get per chapter is the chapter title. Author/s and narrator/s are always given for the entire book.
