### ISSUE TITLE
Book Titles Truncated at first dot

### ISSUE THREAD

**Issue by nurbles** [audiamus/AaxAudioConverter#2]
I just noticed in my output folder that book titles that contain a dot end just before the dot.  So, for example, I have "The Collected Works of Arthur C" instead of "The Collected Works of Arthur C. Clarke".

Looking deeper, I see that titles that should end with "(unabridged)" are missing that word and the parenthesis and the one title I have that contains a colon ends just before the colon.  I kinda understand that one, since a colon is an illegal file name character, but I would prefer it to be replaced with a dash (or some other legal character.)

Again, I know this is a new work and has only recently been released, I'm "beating it up" and reporting what I find in the hope that this changes from a really good tool into a GREAT tool!

**Comment by nurbles** [comment]
Oh, this could be especially troubling for volumes in a series that all end with "Vol. N" because removing the volume number would make all the titles the same!

**Comment by audiamus** [comment]
The dot should be accepted as a valid title punctuation mark indeed. 

However, you can already customize this, in the Basic Settings dialog, via the system menu. You can also, if you want to, add the parentheses there.

But there is some intention behind this behaviour. The title is parsed for non-essential i.e. meta information, and such elements are to be removed, to make it as short as possible. The parsing is very simple at the moment, looking for punctuation marks. My default use case is listening to the audiobook on my car radio and the radio display shows the title tag with a limited number of characters allowed.       

As there are other use cases, I will add more customization options here.  Users may want to have the series title included which is usually separated with a colon. But sometimes the series title is left and sometimes right of the book title. This will be taken care of.

And I will add free text customization on an individual file basis, for author(s) and title. That can also solve the long path issue. (The control I want to use for editing here is the DataGridView. I have worked with that a lot in the past but seem to have forgotten many of the details. So, it'll take while to get back on track.)
