### ISSUE TITLE
Too long a title name

### ISSUE THREAD

**Issue by RusselCrowe67** [audiamus/AaxAudioConverter#20]
With using a long title name like:
Der Tag, an dem die Oma das Internet kaputt gemacht hat , Der Ostermann , Prinzessin Popelkopf
an error occur. Log from newest release 1.10 with log level 3.

[AaxAudioConverter_2020-04-11_001.zip](https://github.com/audiamus/AaxAudioConverter/files/4465198/AaxAudioConverter_2020-04-11_001.zip)

**Comment by audiamus** [comment]
Thank you. Yes, clearly a bug. The program identifies your output device S: as a network drive, which may be correct, but it does not add the UNC prefix \\? to it, which is incorrect. So the path is still limited to 255 characters and that is too short here. It's too late for version 1.10 now to have this fixed but I might release an intermediate release once I've found the cause and have it work as intended. For the time being, shortening the title in the preview dialog to shorten the path, as you did it, is the best way around this bug.  

Danke. Ganz klar ein Fehler. Das Programm sieht das angegebene Ziellaufwerk S: als Netzwerklaufwerk, was durchaus stimmen man, setzt aber nicht den UMC-Präfix \\? davor, was falsch ist. Daher bleibt der Pfad auf 255 Zeichen beschränkt, und das ist hier zu wenig. Für Version 1.10 ist es nun zu spät um das noch beheben zu können, aber es könnte eine Zwischenversion geben, wenn ich die Ursache gefunden habe und es dann wie gedacht durchläuft. Um den Fehler zu umgeben ist es für den Moment wohl wirklich am besten, den Titel im Vorschaudialog zu kürzen, und damit den gesamten Pfad, so wie Du es bereits gemacht hast.

**Comment by audiamus** [comment]
Fixed in version 1.11.

In Version 1.11 behoben.
