### ISSUE TITLE
Activation error

### ISSUE THREAD

**Issue by engdarkalchemist** [audiamus/AaxAudioConverter#200]
I'm unable to convert, I get the error: Activation error. 
I downlaoded aax to my desktop since BookLibConnect does not work (issue reported).
<img width="245" alt="AAXAudioConverter-activationfailed" src="https://github.com/audiamus/AaxAudioConverter/assets/84588028/7a117556-744e-4f03-a926-f12db59737e5">

Note: I use Windows 11.

**Comment by audiamus** [comment]
The classic activation code is required, if you download your book via web browser. A dummy code will only do, if you download with Book Lib Connect, after successfully creating a profile.
