### ISSUE TITLE
accept .mp4 extension

### ISSUE THREAD

**Issue by timadye** [audiamus/AaxAudioConverter#201]
Excellent program, thank you!

When I download from `My Library` on `www.audible.co.uk`, the file is named `something.mp4`. The AAX Audio Converter does not accept the `.mp4` file type, even if I drop it straight into the window. The workaround is easy: rename the file to `something.aax` and it works like a dream.

Can the program be modified to accept `.mp4` in the file name-type?

**Comment by timadye** [comment]
I found this already discussed in #115. Sorry for the duplicate - I am not used to using the github discussions feature.

I'll leave this open as a gentle reminder of that old request. Please feel free to close it immediately if it is not helpful to keep here.

**Comment by audiamus** [comment]
Did you try with a renamed file .mp4 to .aax, then?

**Comment by timadye** [comment]
> Did you try with a renamed file .mp4 to .aax, then?

Yes, and that works fine. Like #115, I hoped this could be handled without this workaround.

Thanks,
Tim.
