### ISSUE TITLE
Virustotal finds a problem

### ISSUE THREAD

**Issue by uvwild** [audiamus/AaxAudioConverter#207]
this is from this release
https://github.com/audiamus/AaxAudioConverter/releases/tag/v1.18.2

![Clipboard_05-25-2024_02](https://github.com/audiamus/AaxAudioConverter/assets/825210/e7460c3c-b7d4-48a9-8317-e7d0a3cb096d)

2 I find quite irritating. I recently downloaded a few printer service mode tools which were positive detected for malware.
Only an older version was clean and reset my canon printer to be used again.

It would really help if someone can explain why this should be a false positive.
I can also imagine things go wrong in the packaging and there is nothing in the repo. 
but 2 hits is

**Comment by audiamus** [comment]
AAX Audio Converter indeed uses Fody, in particular Fody/Costura; https://github.com/Fody/Costura. And it's a GitHub server download and should be so. So, both observations are correct.
