### ISSUE TITLE
AaxAudioConverter throws an exception when run

### ISSUE THREAD

**Issue by Aberdyfi** [audiamus/AaxAudioConverter#208]
I feel guilty about reporting an issue, because AaxAudioConverter is exactly what I have always wanted for handling my audiobooks. Maybe the problem is the user not the program?

I am trying to use AaxAudioConverter on a Windows 7 machine. It installs with no problem, but when I run it I get an exception. The text of the exception is:

> Startup Tip
> Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.
> Value cannot be null. Parameter name: source.

The details are attached in file [Error Details 2.txt](https://github.com/user-attachments/files/15525399/Error.Details.2.txt)

I chose to ignore the error, and the program appears to run fine. However, I think some light on the source of the problem can be gleaned from the fact that I find the following two folders in AppData:

```
C:\Users\Jane Doe\AppData\Local\audiamus\AaxAudioConverter
C:\Users\Jane Doe\AppData\Local\audiamus\AaxAudioConverter.exe_Url_kxobkovw3b2duqowv3y2lnw4xqybgzlu\1.18.2.0
```

The former has empty subfolder `tmp`, and the latter contains what appears to be a functional version of `user.config`.

I note that my version of Windows 7 really is 64 bit.

**Comment by audiamus** [comment]
I believe, this is an issue with Win 7 and some recent security enhancements on GitHub.

The exception is related to the online update function. I have reactivated my last Win 7 system and I can reproduce the exception. Unfortunately, I can't fix this. GitHub is the provider for any AAX Audio Converter updates, and they presumably are now enforcing [TLS ](https://en.wikipedia.org/wiki/Transport_Layer_Security)1.3. While underlying classic .Net Framework 4.8 for AAX Audio Converter supports it, the Windows 7 operation system does not, at least not in conjunction with .Net 4.8.  

You can disable auto-update in the AAX Audio Converter settings and the exception will no longer be thrown. 

_The two (or more) folders in `*\AppData\Local\audiamus\AaxAudioConverter*` are not a problem. Classic .Net 4.8 user settings reside in a folder of their own with every new build of the app. For a user this means he would start afresh with every new version and lose all his previous settings. But AAX Audio Converter takes care of that, adding and managing an additional folder for the settings._

**Comment by Aberdyfi** [comment]
I can confirm what you have said: disabling auto-update in the AAX Audio Converter settings eliminates the error. Also, yes, I encountered issues with TLS in relation to OneDrive. Fortunately OneDrive works with TLS 1.2, and there is an optional update to Windows 7 that gets one to TLS1.2. 
All of which confirms: "AaxAudioConverter is exactly what I have always wanted for handling my audiobooks".
Thank you!
