### ISSUE TITLE
Keep ASIN available after conversation

### ISSUE THREAD

**Issue by patrickwolf** [audiamus/AaxAudioConverter#209]
Today I wanted to see if I could move my books into Genre folders and realized that a) the genre is not included and b) the ASIN that could help me get the genre gets lost through the conversion. 

So I wanted to create a ticket to request to remedy the missing ASIN through one or more of these ways:
if Settings > Conversion > Extra file info is enabled 
- Include the JSON in the output folder (would be the best as it contains much more data that can be retained ie the Genre)
- Include the ASIN in the generated text file (would be helpful in any case even if the json is there)

And also regardless of the setting 
- Include the ASIN in the .m4b metadata

Without the ASIN there is no way to uniquely identify the audio book and later on query more details via the API about it, provide it for a audio book library as a unique id etc.

Thank you,
Patrick

**Comment by patrickwolf** [comment]
For those that desire to keep the JSON files around after conversion here a [gist](https://gist.github.com/patrickwolf/ccb2ae7cf93999cb93c56b378706e2e6) that does exactly that.
And also a [discussion](https://github.com/audiamus/AaxAudioConverter/discussions/210) around this feature request

**Comment by audiamus** [comment]
I have added introducing an optional custom ASIN tag to my todo list.

**Comment by patrickwolf** [comment]
Great thank you @audiamus

**Comment by audiamus** [comment]
Closing for now...
