### ISSUE TITLE
Rename & Sorting of .axx-Files

### ISSUE THREAD

**Issue by Kazaa3** [audiamus/AaxAudioConverter#21]
Hallo audimus,

wäre es möglich ein Feature hinzufügen, dass die .axx-Dateinamen auf Wunsch umbennent. Z.B. nach dem Muster:  "Autor - Buch - Stück", wie es für die .m4b-Dateinamen bereits vorhanden ist. 

Vielleicht auch mit der Option die .axx und .json-Datei in ein Wunschverzeichnis zu kopieren nachdem die .m4b erstellt wurde.

Zum Hintergrund: Wenn man viele Hörbücher besitzt wird der Ordner mit den .axx-Dateien sehr unübersichlich, vorallem da der Windows Explorer die Metadaten nicht auslesen kann. Eindeutige Namen und nach Autor sortierte Dateien, würde den Ordner viel überischtlicher machen.

Podcasts werden nach Folgennr. sortiert, sodass alle Podcasts vermischt sind. Ich würde z.B gerne alle Folgen eines Podcasts auf mein Smartphone kopieren und vorher einen anderen Podcast löschen. Mit eigenständigen Ordnern für Podcasts würde das sehr viel schneller gehen.

**Comment by audiamus** [comment]
Ich habe das mal in die Wunschliste aufgenommen.

Um den Aufwand in Grenzen zu halten, könnte es so aussehen:
- Man wählt ein Verzeichnis, in die alle .aax-Dateien kopiert werden, ähnlich wie für die Konvertier-Ausgabe. Kommt in die Grundeinstellungen, weil doch eher Sonderfunktion und dort einfacher unterzubringen.
- Es werden die Einstellungen und Regeln für die Verzeichnis-/Dateinamen der MP3/MP4-Ausgabe übernommen, aber:
  - Mehrteilige Bücher bleiben natürlich mehrteilig, daher muss die Nummer des Teils hinzugefügt werden. 
  - Enthält der Originaldateiname eine ASIN, wird sie beim neuen Dateinamen ebenfalls mit angehängt. Die ASIN im Dateinamen ist die einzige Möglichkeit, die zugehörige content_meta.json zu finden. (Mit Audible Manager / Download-Helper heruntergeladene Bücher enthalten keine ASIN.)
  - Zugehörige content_meta.json werden in das selbe Verzeichnis kopiert. Nur so kann das Programm sie bei einer späteren erneuten Konvertierung einfach wiederfinden.
- Die AAX-Kopieraktion findet nur statt, wenn der Konvertiervorgang für das gesamte Buch erfolgreich war, also im Anschluss.
- Wird auf AA-Dateien genauso angewandt.

**Comment by audiamus** [comment]
Umgesetzt in 1.11. 

Hat dann doch sein eigenes Namensschema erhalten, aber nach gleichem Muster wie für die anderen Ausgaben.

**Comment by Kazaa3** [comment]
Hab es eben ausprobiert, funktioniert perfekt. Danke.
