### ISSUE TITLE
2.69GB single m4b file cant be played after conversion

### ISSUE THREAD

**Issue by bust4cap** [audiamus/AaxAudioConverter#212]
Im using v1.18.2.0 of AAX Audio Converter. Im trying to convert the German version of the "Shogun" audiobook by James Clavell. Its almost 51 hours long and 2.69GB in size.
I use Book Lib Connect first to download the audiobook, then AAX Audio Converter to get a better formatted m4b file.
Book Lib Connect already creates a single m4b file, and that works perfectly fine, but converting the same AAX file with this software outputs a broken file that cant be played by either media player classic or vlc.
Every other audiobook I tried before worked fine, including longer ones that were over 70 hours long. And converting this title in parts works too.
These are my settings:
![aaxsettings](https://github.com/user-attachments/assets/bba8b76e-4698-4ac8-ad1a-9bbe89bf10ef)

this is the beginning of each file in hex, left is the working file from Book Lib Connect, right is the non working file from AAX Audio Converter:
![shogunhex](https://github.com/user-attachments/assets/1549b9d1-e05d-429f-a798-54b31cf275f8)

**Comment by bust4cap** [comment]
It also took significantly longer to convert. This one file took almost 14 minutes with AAX Audio Converter (2.69GB , ~51 hour runtime), while 2 other files took about 8 minutes combined (which had a combined ~94 hour runtime and were 3.1GB in size)

**Comment by audiamus** [comment]
A log file might tell us more. 

Have you tried to split by chapter?

**Comment by bust4cap** [comment]
split by chapter works perfectly fine.

this is with log level 3
[AaxAudioConverter_2024-08-05_001.log](https://github.com/user-attachments/files/16498520/AaxAudioConverter_2024-08-05_001.log)

log level 4
[AaxAudioConverter_2024-08-05_003.log](https://github.com/user-attachments/files/16498727/AaxAudioConverter_2024-08-05_003.log)

**Comment by audiamus** [comment]
It seems that AAX Audio Converter is using the older 32bit version of FFmpeg here (the default). You could enforce using the 64bit version by modifying `FFmpeg64bitHours` in `C:\Program Files\audiamus\AAX Audio Converter\AaxAudioConverter.exe.config`. Set its value to a number of hours shorter than the runtime of the book in question.

**Comment by bust4cap** [comment]
changed it to 49, made no difference.
updated ffmpeg to the newest version (also 64bit), conversion was about 25% faster, but still not playable

**Comment by audiamus** [comment]
It could be a problem with 3rd party ATL.net which sets the new meta data, both variants, hereby rewriting the .mp4 file. However, there is nothing I can do here for the time being, as AAX Audio Converter has not been migrated to .Net Core yet, but ATL.net has.
