### ISSUE TITLE
Google play books

### ISSUE THREAD

**Issue by losercon** [audiamus/AaxAudioConverter#213]
Is there a way to use this for google play books as well?

**Comment by audiamus** [comment]
I don't know about Google in context with Audible, so I can't comment.

AAX Audio Converter deals with special variants of MPEG4 audio files crated by Audible.

**Comment by losercon** [comment]
oh sorry I meant was it possible to add a downloader for the Google play books audiobooks that you aren't able to export. but no worries if you are just focusing on audible thanks
