### ISSUE TITLE
AaxAudioConverter -to-mp3 with >99 chapters

### ISSUE THREAD

**Issue by Sailfish** [audiamus/AaxAudioConverter#214]
![foobar2000List](https://github.com/user-attachments/assets/6fbf8b20-7638-4885-83da-20243014c2d5)
![foobar2000properties](https://github.com/user-attachments/assets/2ad3cdae-48af-451f-a6f4-b80de3c31174)

Whenever I use AaxAudioConverter to convert an .aax file with over 99 chapters to .mp3 format and play it back on my mp3 player, after it reaches past chapter 10, it jumps to chapter 100 and continues subsequent chapters in progression, i.e., 100, 101,...,1xx. From the chapter list file you can see that AaxAudioConverter only uses 2 digits for tack number but once it reach 100+ it then uses 3 digits. I believe it is this change that misinforms the MP3 player to move to 1.101 after 1.10 instead of 1.11.

The attached foobar2000List.jpg file shows the partial screenshot chapter list. I've edited  to keep the image small. The attached foobar2000properties.jpg file was created by "select all" of the entire chapter list and then selecting the Properties context menu option. With them all selected, all I need to do is delete the 1 in the Disk Number field and foobar2000 will remove the leading Disk Number and leading 0s from all the chapter track numbers. Then if I save the loaded foobar .mp3 file, the audiobook will play each chapter sequentially.

Is there a means to prevent AaxAudioConverter from appending a Disk Number during the conversion?

**Comment by audiamus** [comment]
The disk number is set automatically. It reflects the part number of the original Audible download.

I vaguely remember some old discussion topic about a 99 chapters limit but I do not recall its outcome. Have you tried to convert to .m4b/.m4a?

**Comment by Sailfish** [comment]
The mp3 player (Sansa Clip) is unable to play anything but .aax, .aa and .mp3 files. The real reason I prefer .mp3 file conversions over playing the .aax file is that the converted files are generally 1/3rd the size of the .aax files with no degradation in audio quality.

PS: the foobar2000 workaround is quick and easy to administer so this issue in not any kind of showstopper problem; merely an inconvenience.
