### ISSUE TITLE
audible activation code

### ISSUE THREAD

**Issue by nikolayganovski1** [audiamus/AaxAudioConverter#22]
The program does not run without audible activation code... so I must purchase?

**Comment by audiamus** [comment]
AAX Audio Converter itself is **Free** and **Open Source** software. You cannot purchase it or make "donations".

But to convert your audiobooks, AAX Audio Converter needs to have access to your _Audible_ activation code. This activation code is bound to your Audible account and has been issued by Audible, see below. 

_Excerpt from [README.md](https://github.com/audiamus/AaxAudioConverter/blob/master/README.md):_

### Audible account
AAX Audio Converter needs the user's personal Audible activation code to be able to process his/her Audible audiobooks. The easiest way to obtain the Audible activation code is to install and activate “Audible Manager” or “Audible App”. Audible Manager/App can be downloaded from the Audible website, on the software page. With Audible Manager or App installed and activated, i.e. associated with the Audible account, AAX Audio Converter should be able to find the activation code automatically.

### Anti-Piracy Notice
Note that this software does not ‘crack’ the DRM or circumvent it in any other way. The application simply applies the user's own activation code (associated with his/her personal Audible account) to decrypt the audiobook in the same manner as the official audiobook playing software does.
