### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by araryo** [audiamus/AaxAudioConverter#23]
When executing convert, below exception occurs.
-------------------------------------------------------------
**Exception message:**
System.NullReferenceException: Object reference not set to an instance of an object
위치: audiamus.aaxconv.lib.AudibleAppContentMetadata.findContentMetadataFile(String fileName)
위치: audiamus.aaxconv.lib.AudibleAppContentMetadata.GetContentMetadata(BookPart part, Boolean fileOnly)
위치: audiamus.aaxconv.lib.AaxAudioConverter.getContentMetadata(BookPart part)
위치: audiamus.aaxconv.lib.AaxAudioConverter.verifyActivationAndGetChapters(BookPart part, String activationcode)
위치: audiamus.aaxconv.lib.AaxAudioConverter.checkActivationAndGetChapters(BookPart part)
위치: audiamus.aaxconv.lib.AaxAudioConverter.checkActivationAndGetChapters(Book book)
위치: audiamus.aaxconv.lib.AaxAudioConverter.convertBook(Book book)
위치: audiamus.aaxconv.lib.AaxAudioConverter.<>cDisplayClass70_0.<convertBooksParallel>b2(Book b)
위치: System.Threading.Tasks.Parallel.<>cDisplayClass31_0`2.<ForEachWorker>b0(Int32 i)
위치: System.Threading.Tasks.Parallel.<>cDisplayClass17_0`1.<ForWorker>b1()
위치: System.Threading.Tasks.Task.InnerInvoke()
위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
위치: System.Threading.Tasks.Task.<>cDisplayClass176_0.<ExecuteSelfReplicating>b0(Object <p0>)

**logfile (wiht loglevel=3):**
[AaxAudioConverter_2020-05-15_001.zip](https://github.com/audiamus/AaxAudioConverter/files/4634255/AaxAudioConverter_2020-05-15_001.zip)

**Screen shot:**
![image](https://user-images.githubusercontent.com/19299395/82048447-aa7eac80-96ef-11ea-8d55-a0df322e471c.png)

**Comment by audiamus** [comment]
Thank you. The log file helps.

The problem for AAX Audio Converters is that your input file resides at the root level of drive D. The program tries to find the parent directory, which does not exist.

Try to move the aax file somewhere lower, with at least one directory level above it, like 
`D:\tmp\Aesop’s Fables_B007H914RU_LC_64_22050_Stereo.aax` 
or similar.

This is a bug. I will fix it in the next version.

**Comment by araryo** [comment]
It works!!, thank you for your efforts.
AaxAudioConverter is the best free converting tool ^^

**Comment by audiamus** [comment]
Very good. And thanks for the compliments. 

Already fixed in the code. Will be released with 1.12
