### ISSUE TITLE
Missing chapter names in .m4a

### ISSUE THREAD

**Issue by jth** [audiamus/AaxAudioConverter#25]
Hi,

after converting an audible .aax file (chapter names are visible in Audible app), I end up without chapter names (just a number or "chapter X", depending on whats setup). I convert to mp4 and use foobar2000 as player, which shows each chapter as individual track, so the chapter marks are still intact I assume.

However, I'am not too familiar with the AAX-format, it might also be the case that the information is simply missing from the AAX file.

For example, ffprobe shows the following when used with `-show_chapters`
```
Duration: 04:30:48.31, start: 0.000000, bitrate: 128 kb/s
    Chapter #0:0: start 0.000000, end 193.956281
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 193.956281, end 1170.146395
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 1170.146395, end 2199.672744
    Metadata:
      title           : Chapter 3
    Chapter #0:3: start 2199.672744, end 3283.092608
    Metadata:
      title           : Chapter 4
    Chapter #0:4: start 3283.092608, end 4437.333333
````

Now the Audible app has the correct chapter names and they have to come from some location.

Any idea on whats going on here is appreciated. Maybe I'am using the tool wrong, the chapter names are missing from the AAX-file or it's something else?

**Comment by jth** [comment]
Typical case of RTFM, chapter 2.4 in the manual states how the chapter names work. I think the issue can be closed since it's not a problem with AaxAudioConverter

**Comment by audiamus** [comment]
Explicit chapter names are to be found in `content_metadata_<ASIN>.json`. That's where the Audible App takes them from and AAX Audio Converter does the same, if it can locate that file and if this option has not been disabled in the settings.

I'm glad to hear that the manual has been useful.  :smile:
