### ISSUE TITLE
Enhancement Request: No chapter folders

### ISSUE THREAD

**Issue by sab666** [audiamus/AaxAudioConverter#26]
As a user, I would like to be able to split the output into multiple files at approximate intervals AND at the start of a new chapter, while also putting all files into the same directory.

My suggestion for making this an option in the User Interface is to add an option to the `Chapter folders name prefix`, called `<No chapter folders>`. (Though in that case it might be better to rename that optiongroup to `Chapter folders`).

Furthermore I want to thank you for this software. As someone who has done a fair bit of conversion of media myself, I can appreciate all the effort that went into this, and the trouble that it saves regular users.

**Comment by audiamus** [comment]
I'll have to check this. It will collide with one of the track naming patterns: `<chapter>.<track>` as chapter names don't have to be unique.

**Comment by audiamus** [comment]
_Update:_

It's doable and will be implemented in the next version. To solve the problem of non-unique file names, the potentially conflicting settings in the property grid will mutually exclude each other. No big fuss here, if you try to set a value which is currently not allowed, we just play the error sound and ignore the requested change.

I will leave the wording `Chapter folders name prefix` as it is. The new option will display as `(no chapter sub-folders)`. Three of the four values are prefix rules, one is not. Majority wins :smiley_cat:.

**Comment by sab666** [comment]
That's excellent news! Thank you for picking this up so quickly.

**Comment by audiamus** [comment]
Implemented in release 1.13.
