### ISSUE TITLE
Possible to build for older .NET Framework versions so that this works with Wine in Linux?

### ISSUE THREAD

**Issue by basnappl** [audiamus/AaxAudioConverter#28]
Would it be possible to build this for, say, .NET 4.5?

**Comment by audiamus** [comment]
Why does it have to be an older .Net Framework?

According to WineHQ, 4.7.1 is supported: https://appdb.winehq.org/objectManager.php?sClass=version&iId=36188
There are also a few Win32 API calls via PInvoke, but those may also be supported by Wine.

**Comment by basnappl** [comment]
Oh, I see.  I could not get it working and thought that this was the reason but apparently I just did something wrong.  Thanks!
