### ISSUE TITLE
Activationbytes Lib

### ISSUE THREAD

**Issue by JKamsker** [audiamus/AaxAudioConverter#29]
I've created a free service which resolves the activation bytes of any hash possible. 
It's netstandard 2.0 so it should be compatible.

I have tryed to do a pr myself but i constantly run into issues understanding and compiling your code, so i kindly ask you doing that.

Nuget package: https://www.nuget.org/packages/Aax.Activation.ApiClient/1.0.0
How to use: https://github.com/JKamsker/OSAC/blob/master/OSAC/MainWindow.xaml.cs#L172

**Comment by audiamus** [comment]
Thank you very much for your suggestion.

Unfortunately, it would violate the anti piracy policy of AAX Audio Converter (see [README.md](https://github.com/audiamus/AaxAudioConverter/blob/master/README.md)):
> Note that this software does not ‘crack’ the DRM or circumvent it in any other way. The application simply applies the user's own activation code (associated with his/her personal Audible account) to decrypt the audiobook in the same manner as the official audiobook playing software does.

**Comment by JKamsker** [comment]
Oh, ok then you can close this issue :/
