### ISSUE TITLE
Directory names with dot at the end

### ISSUE THREAD

**Issue by xBlairx** [audiamus/AaxAudioConverter#3]
There is a problem using Windows when directory names are ending with a dot. You cannot access, rename or delete those directories in Windows.

This happens when the author is like "div." or something else.

Removing such a directory just works with a little workaround: 
rd /s "\\\\?\d:\audio\directorywithdotatend."

**Comment by audiamus** [comment]
Thanks a lot. Never realized that trailing dots cause a problem, but they do indeed. I will address it, and perhaps prevent leading dots as well.

**Comment by audiamus** [comment]
Solved in version 1.3.1.
Trailing and leading dots will automatically be removed for folder names.
