### ISSUE TITLE
Error ffmpeg

### ISSUE THREAD

**Issue by darkwebguy1** [audiamus/AaxAudioConverter#30]
I can't get this file to work. I either get prompts that ffmpeg stopped working or I get error operation abort. 
[log.zip](https://github.com/audiamus/AaxAudioConverter/files/5139882/log.zip)

**Comment by darkwebguy1** [comment]
Figured it out, the file didn't download properly.

**Comment by audiamus** [comment]
Thank you for uploading the log files. Indeed, FFmpeg reported tons of decoding errors.
