### ISSUE TITLE
"Windows protected your PC"

### ISSUE THREAD

**Issue by zylstra** [audiamus/AaxAudioConverter#32]
I get a "Windows protected your PC" dialogue box alert when I attempt to install AAX Audio Converter.  The box says further, "Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk."

Why does this happen?  I have not seen this before, and I install a lot of software.

**Comment by zylstra** [comment]
Please delete.  I think it's malware?

**Comment by audiamus** [comment]
> Why does this happen? I have not seen this before

I haven't either. The installer is not digitally signed and therefore Windows will ask you (twice) whether to proceed with the installation. Apparently, your version of Windows adds an additional caution mark to the executable. 

Are you able to unblock the .exe (via Properties)?

To verify the integrity of the installer you can compare the MD5 hash. The MD5 reference value will be found here:
https://github.com/audiamus/AaxAudioConverter/blob/master/res/Setup.dat
(That's what the automatic update mechanism is doing.)

And, as this is an Open Source project, you can also build the executable yourself, from the source files.

**Comment by zylstra** [comment]
OK, thanks.
