### ISSUE TITLE
No Sound after conversion

### ISSUE THREAD

**Issue by MabeyC** [audiamus/AaxAudioConverter#35]
Hello,

I have attempted to convert a few dozen audio books, but the mp3 files created contain no audio. Maybe I've missed a setting somewhere?

Windows 10 (virtual machine) - Audible app downloaded and activated.
Aax Audio Converter v1.15.1

Steps taken:
Set up Windows 10 virtual machine.
Downloaded and installed Audible win 10 app via MS Store. 
Signed in to audible app. 
Downloaded and installed AAX Audio Converter.
When loading, I was not prompted to enter activation code.
Converted track (Source of downloaded audible file was not downloaded via Win 10 app, but via their site on another PC)
[screencap]
![Convert Settings](https://user-images.githubusercontent.com/55720817/98454387-51da1a80-213a-11eb-8cdb-162ecdb4ac13.PNG)

I initially thought that maybe by not downloading the audio book from the app may have cause some issue, so I tried downloading a title via the Win 10 app and converted that. Same effect: no sound.

Then I thought that since there was an update, that I should check that too. 

I updated to 1.15.2 and tried again; same thing.

Any help would be greatly appreciated.

**Comment by audiamus** [comment]
No error message? 
MP3 files have been created? 
Did you try more than one player? 
Did you run some analysis tool, like MediaInfo?

**Comment by MabeyC** [comment]
No error messages. 
Completed successfully each time. 
MP3 files are created and named as expected.
Attempted to play audio on Groove Music (Windows 10), Celluloid and Audacious (Linux Mint)
I downloaded MediaInfo and added one of the media files, below is the debug info:

General
Count :
332
Count of stream of this kind :
1
Kind of stream :
General
Kind of stream :
General
Stream identifier :
0
Inform :
MPEG Audio: 1.12 MiB, 2 min 22 s
Count of audio streams :
1
Audio_Format_List :
MPEG Audio
Audio_Format_WithHint_List :
MPEG Audio
Audio codecs :
MPEG Audio
Complete name :
Desktop/Audiobooks/Ryan James - Copy/Speed Reading/Chapter 1 - Speed Reading - Ryan James.mp3
Folder name :
Desktop/Audiobooks/Ryan James - Copy/Speed Reading
File name extension :
Chapter 1 - Speed Reading - Ryan James.mp3
File name :
Chapter 1 - Speed Reading - Ryan James
File extension :
mp3
Format :
MPEG Audio
Format :
MPEG Audio
Format/Extensions usually used :
m1a mpa mpa1 mp1 m2a mpa2 mp2 mp3
Commercial name :
MPEG Audio
Internet media type :
audio/mpeg
File size :
1172303
File size :
1.12 MiB
File size :
1 MiB
File size :
1.1 MiB
File size :
1.12 MiB
File size :
1.118 MiB
Duration :
142101
Duration :
2 min 22 s
Duration :
2 min 22 s 101 ms
Duration :
2 min 22 s
Duration :
00:02:22.101
Duration :
00:02:22.101
Overall bit rate mode :
CBR
Overall bit rate mode :
Constant
Overall bit rate :
64000
Overall bit rate :
64.0 kb/s
Stream size :
35495
Stream size :
34.7 KiB (3%)
Stream size :
35 KiB
Stream size :
35 KiB
Stream size :
34.7 KiB
Stream size :
34.66 KiB
Stream size :
34.7 KiB (3%)
Proportion of this stream :
0.03028
Title :
Chapter 1 - Speed Reading
Album :
Speed Reading
Album/Performer :
Ryan James
Part/Position :
1
Part/Total :
1
Track name :
Chapter 1 - Speed Reading
Track name/Position :
2
Track name/Total :
18
Performer :
Ryan James
Publisher :
Ryan James
Genre :
Audiobook
Recorded date :
2017
File last modification date :
UTC 2020-11-08 00:38:28
File last modification date (local) :
2020-11-07 20:38:28
Writing library :
LAME3.100
Writing library :
LAME3.100
Copyright :
©2017 Ryan James (P)2017 Ryan James
Cover :
Yes
Cover description :
cover.jpg
Cover type :
Cover (front)
Cover MIME :
image/jpeg
Comment :
Find out what your current reading level is, and learn how to incorporate the exercises and techniques found in this audiobook into your daily routine so that speed reading becomes a habit. Soon you will find that you can read an entire book each day! The more you read, the more knowledge you will gain that you can use to achieve your goals in life.
Musician Credit List :
Author
Audio
Count :
280
Count of stream of this kind :
1
Kind of stream :
Audio
Kind of stream :
Audio
Stream identifier :
0
Inform :
64.0 kb/s, 22.05 kHz, 2 channels, MPEG Audio (Version 2) (Layer 3) (Joint stereo / MS Stereo)
Format :
MPEG Audio
Format :
MPEG Audio
Commercial name :
MPEG Audio
Format version :
Version 2
Format profile :
Layer 3
Format settings :
Joint stereo / MS Stereo
Mode :
Joint stereo
Mode extension :
MS Stereo
Internet media type :
audio/mpeg
Duration :
142106
Duration :
2 min 22 s
Duration :
2 min 22 s 106 ms
Duration :
2 min 22 s
Duration :
00:02:22.106
Duration :
00:02:23:06
Duration :
00:02:22.106 (00:02:23:06)
Bit rate mode :
CBR
Bit rate mode :
Constant
Bit rate :
64000
Bit rate :
64.0 kb/s
Channel(s) :
2
Channel(s) :
2 channels
Samples per frame :
576
Sampling rate :
22050
Sampling rate :
22.05 kHz
Samples count :
3133440
Frame rate :
38.281
Frame rate :
38.281 FPS (576 SPF)
Frame count :
5440
Compression mode :
Lossy
Compression mode :
Lossy
Stream size :
1136808
Stream size :
1.08 MiB (97%)
Stream size :
1 MiB
Stream size :
1.1 MiB
Stream size :
1.08 MiB
Stream size :
1.084 MiB
Stream size :
1.08 MiB (97%)
Proportion of this stream :
0.96972
Writing library :
LAME3.100
Writing library :
LAME3.100

**Comment by MabeyC** [comment]
Other PC's did not reproduce error. I believe this to be an issue from my PC.

Thanks for taking the time to respond, and for creating this application. Thank you!

**Comment by audiamus** [comment]
Thanks for the update on the issue.

I find MediaInfo always helpful. It can't detect everything in media files but it usually gives you a good overview.

**Comment by Dudeman456** [comment]
I have this issue as well. Except that I use AAX Audio Converter to convert to chapterized M4B. The ones I converted in the last few months do not have sound. When I installed the AAX Audio Converter program on a different computer using the dummy code, the conversion gave me an error but the M4B it output had sound. I should mention I have been using Libation to download.

**Comment by Dudeman456** [comment]
To add to this, I tried converting to MP3, and that failed with an FFMPEG error, so perhaps at some point the configuration of AAX Audio Converter became corrupted and is not decrypting the AAX files.

**Comment by audiamus** [comment]
Original AAX files can only be decrypted with the proper activation code, otherwise FFmpeg will throw an error.

I don't know how Libation downloads and decrypts Audible books but I believe it uses AAXClean for decryption, just as my [BookLibConnect ](https://github.com/audiamus/BookLibConnect) does. In any case, I suggest to try downloading with BookLibConnect.

**Comment by Dudeman456** [comment]
Thanks for the reply. The thing that I don't understand is that on the other computer using the dummy code, it decodes and makes a proper M4B file. I am re-doing my entire library right now with BookLibConnect.
