### ISSUE TITLE
Feature Request: Create a Mac Version

### ISSUE THREAD

**Issue by linuxr01** [audiamus/AaxAudioConverter#36]
Hello, is it possible to create a Mac Version?

**Comment by audiamus** [comment]
I'm afraid not. 

But as far as I understand, you should be able to run a virtual Windows system on your Mac and run the program there.

**Comment by linuxr01** [comment]
ok :(

**Comment by audiamus** [comment]
Isn't Wine supported on MacOS?

**Comment by linuxr01** [comment]
Its possible with VirtualBox. The Problem is the new MacBooks are ARMs.

**Comment by DoctorVanGogh** [comment]
> I'm afraid not.

*Technically* a refactor to .NET Core 3 using a cross platform XAML based UI like [AvaloniaUI](https://github.com/AvaloniaUI/Avalonia) would run *perfectly fine* on Max or Linux ;) (Or you could wait for .NET 6 which - as of now - is promised for Nov. 2021).

Heck, even the underlying Ffmpeg is supported on those platforms.

**Comment by Iraaazer** [comment]
@DoctorVanGogh it seems you are very good informed about new C# technologies. So it could be that you are a software developer yourself. Why don't you fork this project and make it cross-platform. The idea of open source is, that every one who has a good idea and the ability to implement them can do it. The result is a even better Software. In your comment you show a possible way yet.
