### ISSUE TITLE
unwanted overwriting of previous result behaviour

### ISSUE THREAD

**Issue by typxxi** [audiamus/AaxAudioConverter#4]
I have purchased a book and downloaded it with audible app.
I got 4 fuge files and started with the first big file.

AaxAudioConverter tooks its time and worked fine resulting in a folder 1 with nearly 50 mp3 files in right order

Great.

So I went back and marked the other 3 huge files and started the conversion. 
Then a warning appeared that a book of the author already exists and it offered cancel or overwrite if I remember correctly. 
I knew that I had not chosen the first file to convert again that could result in a loss of previous files but here it comes:
At least folders inside the authors folder were SIMPLY DELETED, not overwritten !

My files were stored in \Author A\1  folder and when I started the conversion of part 2 to 4 the next moment my already renamed and retagged files inside folder 1 were gone.

No folder  "1" anymore. 

It felt like something was wrong - in my opinion cause the deletion of already converted files should not have happened that way if I did not select the first source file again.

When transcoded I also used mp3tag to get the right titles for each mp3 cause that is important for most of us. I am on 1.4 downloaded today and I guess the i3 will run 1 process on each core cause I can see 4 different track numbers in progress.

**Comment by audiamus** [comment]
Do I understand you correctly that this is a multipart book?

If yes then please try to load all parts into AaxAudioConverter, select them all (Ctrl+A as a shortcut), and start the conversion. AaxAudioConverter should detect the multi-part book and automatically merge the parts into one book folder, with consecutive chapters and track numbers and a single playlist. 

I have to admit that I did not thoroughly test converting individual parts in separate invocations. I regarded converting individual parts more as a trial run, where you want to see some output without waiting too long for the complete result.  

> When transcoded I also used mp3tag to get the right titles for each mp3 cause that is important for most of us

Didn't AaxAudioConverter do that for you?

>  I guess the i3 will run 1 process on each core cause I can see 4 different track numbers in progress.

Correct.

**Comment by audiamus** [comment]
Version 1.5 improves individual part handling. Already existing parts will no longer be deleted.
