### ISSUE TITLE
AAX Audio Converter flags error message on some .aa file types

### ISSUE THREAD

**Issue by Sailfish** [audiamus/AaxAudioConverter#40]
I've removed this issue's post from kettenfett's Issue and included it here.

Environment: Windows 7 SP1 (64bit), AaxAudioConverter-1.15.3.0

Ref: https://imgur.com/CSNv4kW
 
As mentioned in a prior Gitter post, I have over 1000 titles in my library and installed AAX Audio Converter 1.15.3.0 (AAC) and have encountered a problem when attempting to load AAC with my files (no conversion attempted as yet.) it seems to load all my .aax files fine but runs afoul with .aa files while attempting to load them. The link above is to a series of images that should help in explaining the problem. So, when I attempted to load them en masse, I received the error popup periodically (a dozen times or so) as it was loading them. However, it continued on and finally loaded the rest. The error message hadn’t listed the offending file names so I performed a series of chunk loads until I was able to isolate one chuck that manifested the error. After whittling it down I just loaded 3  to make it easier to identify the problem. Image 1 is the Windows File Manage where I’ve selected the 3 files to DnD onto AAC, image 2 is the AAC error message that occurs when loading and image 3 is AAC after selecting OK to close the error message. Note that AAC did load 2 of the 3 fine but found issue with the 3rd. I should mention that this also occurs if I just load the one offending file. However, the file seems to play fine within Media Player or Audible Manager. Even so, since AAC only flags a dozen or so .aa files, it very well may be something strange about just those. If so, I wouldn’t mind re-downloading them in .aax format (since Audible no longer support Format 4(.aa) format but attempt to isolate which ones are causing the error with over 1000 titles would be error-prone and tedious. So, would you be able to list the .aa file name in the error popups so that I could easily know which titles to re-download?

I've attached the log file as requested but only included the error from the one I initially reported to keep it length more manageable. I can also run AAC on my entire .aa titles if you'd prefer. I was also pleased to see that the log file included the name of the offending .aa file so wouldn't mind re-downloading the offending title in .aax format if you prefer. I'll await further instructions.

Best Regards,
Pat[rick]

**Comment by audiamus** [comment]
> I've attached the log file as requested 

Where can I find it?

**Comment by Sailfish** [comment]
That's odd? I know I used the "Attach files by dragging & dropping, selecting or pasting them." feature below. ah, I see now that the attachment didn't work with an older version of Firefox that I was using. I will be using it again but since the log is short I will also add it here. Let me know if you receive the attachment.

AaxAudioConverter_2020-12-12_001.log contents follows:
08:31:22.023 0001 Level=3
08:31:22.097 0001 [MainForm..ctor] AaxAudioConverter 1.15.3.0 on Windows 6.1.7601
08:31:22.111 0001 [ActivationCode.init] add from registry (#=8)
08:31:22.112 0001 [ActivationCode.init] #unique=8
08:31:22.113 0001 [AaxAudioConverter.cleanTempDirectory] "\\?\C:\Users\USER\AppData\Local\audiamus\AaxAudioConverter\tmp"
08:31:22.192 0005 [FileAssoc.Associate] 
08:31:22.194 0001 [AaxAudioConverter.VerifyFFmpegPath] dir="I:\Program Files\Multimedia Design\Audio\AAX Audio Converter"
08:31:22.279 0001 [AaxAudioConverter.VerifyFFmpegPath] version 4.2.2
08:31:22.674 0001 [OnlineUpdate.UpdateAsync] server=1.15.3
08:31:30.099 0013 [AaxAudioConverter.addFilesParallel] "I:\Users\Dad\Music\Audible\Downloads\DeadSixPart1_mp332_ARKLXNBG8DW1U.aa"
08:31:30.099 0011 [AaxAudioConverter.addFilesParallel] "I:\Users\Dad\Music\Audible\Downloads\DeadSixPart2_mp332_ARKLXNBG8DW1U.aa"
08:31:30.099 0007 [AaxAudioConverter.addFilesParallel] "I:\Users\Dad\Music\Audible\Downloads\DeadSixPart3_mp332_ARKLXNBG8DW1U.aa"
08:31:30.101 0013 [TagAndFileNamingHelper.readMetaData] 
08:31:30.101 0007 [TagAndFileNamingHelper.readMetaData] 
08:31:30.101 0011 [TagAndFileNamingHelper.readMetaData] 
08:31:30.102 0013 [TagAndFileNamingHelper.readMetadataFFmpeg] "I:\Users\Dad\Music\Audible\Downloads\DeadSixPart1_mp332_ARKLXNBG8DW1U.aa"
08:31:30.102 0007 [TagAndFileNamingHelper.readMetadataFFmpeg] "I:\Users\Dad\Music\Audible\Downloads\DeadSixPart3_mp332_ARKLXNBG8DW1U.aa"
08:31:30.102 0011 [TagAndFileNamingHelper.readMetadataFFmpeg] "I:\Users\Dad\Music\Audible\Downloads\DeadSixPart2_mp332_ARKLXNBG8DW1U.aa"
08:31:30.182 0013 [TagAndFileNamingHelper.readMetadataTaglib] 
08:31:30.182 0007 [TagAndFileNamingHelper.readMetadataTaglib] 
08:31:30.184 0011 [TagAndFileNamingHelper.readMetadataTaglib] 
08:31:30.190 0013 [TagAndFileNamingHelper.readMetadataTaglibAudible] "I:\Users\Dad\Music\Audible\Downloads\DeadSixPart1_mp332_ARKLXNBG8DW1U.aa"
08:31:30.190 0011 [TagAndFileNamingHelper.readMetadataTaglibAudible] "I:\Users\Dad\Music\Audible\Downloads\DeadSixPart2_mp332_ARKLXNBG8DW1U.aa"
08:31:30.194 0007 [TagAndFileNamingHelper.readMetadataTaglibAudible] "I:\Users\Dad\Music\Audible\Downloads\DeadSixPart3_mp332_ARKLXNBG8DW1U.aa"
08:31:30.204 0007 [AaxAudioConverter.exceptionCallback] ArgumentNullException:
"Value cannot be null.
Parameter name: array"

[AaxAudioConverter_2020-12-12_001.log](https://github.com/audiamus/AaxAudioConverter/files/5683426/AaxAudioConverter_2020-12-12_001.log)

**Comment by audiamus** [comment]
Thank you. It appears to be related with the initial reading of the meta data. I will investigate.

**Comment by Sailfish** [comment]
As an aside, using the "-Log=3" command line switch on all the *.aa titles in my library, I was able to ID and isolate the 14 files that have exhibited this problem. I can run AAC with just those files and send that log file if you think it would be of help.

Also, if you find something and wish me to test it out, I will be able to efficiently do so with just-Log=3 those files.

**Comment by audiamus** [comment]
AAX Audio Converter uses a 3rd party library to extract the meta data, not FFmpeg directly. Nonetheless it might help to see what FFmpeg does with it. Can you try two things please:

1. Run the following command from a console window:
`<path to>\ffmpeg.exe -hide_banner -i <offending file>.aa 2> out.txt`
FFmpeg.exe will be in the same folder as AAXAudioConverter.exe.
One of the problematic files appears to be `DeadSixPart3_mp332_ARKLXNBG8DW1U.aa`

2.  Run the original AAX Audio Converter session again, but this time with log level 4 and let's see how and if FFmpeg will be involved.

**Comment by Sailfish** [comment]
[DeadSixPt3Out.txt](https://github.com/audiamus/AaxAudioConverter/files/5689363/DeadSixPt3Out.txt)
[AaxAudioConverter_2020-12-14_001.log](https://github.com/audiamus/AaxAudioConverter/files/5689372/AaxAudioConverter_2020-12-14_001.log)

Per your request, attached are the item 1 ffmpeg output file and your AAC log file.

Note: apologies for mixing two issues in my response earlier. I've deleted that response and broke them into responses to the appropriate issues separately.

**Comment by audiamus** [comment]
Thank you again. That's all I need at the moment. At first glance, there is nothing unusual in the FFmpeg output. I will have to dig into the source code.

**Comment by audiamus** [comment]
It could be the cover image. Audible has used more than one way of embedding the cover image into the .aa file. AAX Audio Converter is aware to two methods, but neither might fit here.

I will handle this exception differently in the next version, to allow such books to be loaded even without the cover image.

For the moment I recommend to download the .aax variant.

**Comment by Sailfish** [comment]
Okay, seeing how fast the aax transcoding work versus .aa, I have already decided to go ahead and download the aax version for all author titles I have flagged as worth listening to again. With well over 1000 titles, and most of them flagged as worthy, that will be a daunting task but one, ultimately, be worth it.

Thanks for your time on this.
