### ISSUE TITLE
Title flips on colon

### ISSUE THREAD

**Issue by anesone** [audiamus/AaxAudioConverter#42]
When I convert files with a ":" in them, the first part and the second part are flipped.
E.g., George Lucas: A Life
On the preview screen, it shows;
Source - George Lucas: A Life
Tag - A Life: George Lucas
File - A LIfe: George Lucas 

Is there a setting that will prevent it from flipping?  Or, only use the part before the ":" as the file name?

**Comment by audiamus** [comment]
The colon often separates series title from book title. It is interpreted as such by default. You should be able to alter the behavior with the "Long book title" option within the "Naming" property grid in the main window.  

There is also a tool tip for this option with a brief explanation for each setting, More information can be found in chapter 3.4 of the manual.
