### ISSUE TITLE
How to get file names to start with 01, 02, 03?

### ISSUE THREAD

**Issue by KvnMlkn** [audiamus/AaxAudioConverter#50]
Hello. 1st of all, thanks so much for this software, it's awesome!
How do I get individual files of a given book to be named 01 - xxx, 02 - xxx, and so on? In file explorer, there is a column named "#", which has those numbers. How do I get those to be a the start of the actual file names? 
(question applicable when I select "multiple files, by chapter", of course)
Thank you!

**Comment by audiamus** [comment]
In the "Naming" group in the main window, set the "File naming pattern" to one of the options with `<track>` first and set "Track numbering pattern" to either `<track>` or `<track>(<chapter>)`.
