### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by MKE1138** [audiamus/AaxAudioConverter#51]
Any hopes that a version for macOS will happen?

**Comment by audiamus** [comment]
That's very unlikely, I'm afraid. 

The .Net platform which I am using for AAX Audio Converter is Windows only. While parts of .Net have been ported to .Net Core and have become multi-platform, the GUI components have not. There are plans by Microsoft and Xamarin to develop a new multi-platform GUI toolkit, but that will be quite different from Windows Forms in use here at the moment and would most probably mean to rewrite half of the application code from scratch. Furthermore, I don't know anything about the macOS platform, let alone how to develop software for it.
