### ISSUE TITLE
Checksum Solver

### ISSUE THREAD

**Issue by ueen** [audiamus/AaxAudioConverter#52]
Wouldnt it be possible to integrate a checksum solver?
Like this one https://audible-tools.github.io/
seems really easy and quick, would make aax to mp3 conversion just one step easier.
Otherwise: Great application, thank you very much!

**Comment by audiamus** [comment]
Thank you very much for your suggestion. But it would violate my anti-piracy policy. See #29.

**Comment by ueen** [comment]
Well isn't this program removing DRM anyway? And isn't that also legal for private uses to files you own (at least in some country's)?

**Comment by audiamus** [comment]
Sorry, this is my standing policy and it's not going to change.

**Comment by ueen** [comment]
I don't think adding this feature wouldn't change anything regarding the DRM issue (DRM file in -> mp3 out). But it's your choice :)
