### ISSUE TITLE
Track numbering pattern option for track and chapter does not preceed with track # as selected

### ISSUE THREAD

**Issue by tastyratz** [audiamus/AaxAudioConverter#54]
In my use case, I'd like the option to have BOTH track number and chapter name. When importing audiobooks to podcast addict it does not recognize track number and sorts by file/track/etc. name.  This means I might see intro last, subsections out of order, etc. I could prevent this if my files/tags preceeded named chapters with track numbering. When selecting "Track numbering pattern" <track>(<chapter>) I see no change in the output. I also see no option for just <track> - <chapter>

 I would like to have track number preceed chapter name so that the books can sort alphabetically and be chronologically correct for import into some applications.

**Comment by audiamus** [comment]
Does this mean, your player does not recognize a playlist?

Which conversion mode are you using? The folder structure and file naming/numbering may depend on that.

Have a look at #50 for a possible track and file naming pattern with track number first.

If you download with the Audible App, your books have associated JSON meta data and you "Use name chapters" (Basic Settings), you can also try to set that option to "Yes, always precede with number".

**Comment by tastyratz** [comment]
It does not appear that the playlist was recognized. The player imports the entire folder by contents and displays it by a chosen default sort order such as file name, track name, oldest, largest, remaining minutes. If you play an item in there it then chooses next in line by the sort order chosen.

I'm doing multiple files, by chapter, in M4A format directly from the Audible app content folder. When I choose that naming pattern it has no impact to the end result. chapter names are added, but, track numbers get omitted. Choosing both appears to me to be non-functional in my end result.

**Comment by tastyratz** [comment]
> (Basic Settings), you can also try to set that option to "Yes, always precede with number".

That appears to have worked! It's a bit confusing in the basic settings page especially since it conflicts with the selection mentioned in #50 which does not for me change the end result (bug?), but, the end result was usable for me. Thanks!

**Comment by audiamus** [comment]
Good to hear that.

There are quit a few factors contributing of the file name. I won't list them all here as I would have to check myself with all the possible combinations again. 

The main element here is whether chapter meta data comes from the AAX file or the JSON file. If AAX only, then chapters are mere numbers. With _chapter mode_ that means alphabetical file name order equals chronological order. However, with the JSON file and explicit chapter names/titles, there is no guarantee anymore that alphabetical and chronological order are the same. The only requirement is that file names are unique (and the program will ensure that). Chronological order is established by the playlist. If your player does not support the playlist, you can use the _Always precede with number_ setting for _Use named chapters_ as you now did.

The _Track numbering pattern_ setting in the main window only affects _split-chapter mode_. It's mentioned in the manual, but not as prominent as it should be, and is not mentioned in the tool tip / description of that property. I didn't realize that yesterday either, as split-chapter is the mode I use and then the track number/chapter combo does work.  I will clarify this with the next release.
