### ISSUE TITLE
Proper number ordering of books

### ISSUE THREAD

**Issue by Sabre142** [audiamus/AaxAudioConverter#57]
When I try to convert all of these .aax files at once, it will prioritize 1, 10 and 11 first ahead of 2-9. This leads to wrong ordering of this particular book

![image](https://user-images.githubusercontent.com/26516348/107841943-9e0cb900-6e13-11eb-9997-c091dffc536c.png)

**Comment by audiamus** [comment]
Thank you for reporting this. I wasn't aware of books with more than 9 parts. :astonished:

I have just fixed this now for upcoming version 1.16.

It was going wrong in two places. 

1. The order in the list view. While some of the other columns have tags behind them that allow proper sorting, the book title column had not. So sorting was strictly alphabetically. In 1.16 the part number extractor will be called here and a tag formed that adds padding zeros to the part number. You won't see them, it's for the sorting tag only. We can then have up to 9999 parts.
2. Conversion itself. I would have thought that the parts were already sorted by the part number, whatever the title says. But that was not the case. Fixed there as well.
