### ISSUE TITLE
[Request] Support non-administrative installs

### ISSUE THREAD

**Issue by Abablabab** [audiamus/AaxAudioConverter#58]
### Issue: 

Right now the `PrivilegesRequired=admin` in the Inno configuration means the installer requests administrative privilages even when configured for unprivilaged paths or [executed with RunAsInvoker](https://superuser.com/questions/171917/force-a-program-to-run-without-administrator-privileges-or-uac)

### Suggestion:

According to the [Inno Installer documentation ](https://jrsoftware.org/ishelp/index.php?topic=setup_privilegesrequiredoverridesallowed) this could be as simple as adding:

`PrivilegesRequiredOverridesAllowed=commandline dialog` to the `[Setup]` block in the .iss file. Which would allow users to specify the `/CURRENTUSER` flag to run the installer in a nonprivilaged mode

_P.S. I would have raised a PR but I was unable to replicate your build enviroment, so I cannot promise the change is painless :)_

**Comment by audiamus** [comment]
Thanks for this suggestion. I have put it on the wish list and will try it out for the next version.
