### ISSUE TITLE
activation code

### ISSUE THREAD

**Issue by hhumas** [audiamus/AaxAudioConverter#6]
how to get activation code . 

does it support conversion of PSF to any other audio like flac / mp3

**Comment by audiamus** [comment]
> how to get activation code

The activation code is linked to your Ausdible subscription. The easiest way to obtain the Audible activation code is to install and activate “Audible Manager” or “Audible App”.

> does it support conversion of PSF to any other audio like flac / mp3

AaxAudioConverter supports .aax and .aa as input and .mp3 or .m4a as output.

See also the [readme](https://github.com/audiamus/AaxAudioConverter) and the pdf documentation.
