### ISSUE TITLE
Series Grouping

### ISSUE THREAD

**Issue by necrogami** [audiamus/AaxAudioConverter#62]
Is there a way to get the series / book number in series, i know this info is available in places. Partially in title maybe in extra metadata from the windows 10 audible download. 

Ideal outcome

Folder:
S.H. Jucha/The Silver Ships/10 - Vinium/<Chapters>

**Comment by audiamus** [comment]
> Partially in title maybe in extra metadata from the windows 10 audible download.

It won't work with the embedded book titles. Their format is not consistent. 

I had a look at the json files again. The chapter meta file does not have that info. But there is another json file in the SimsBySeries folder which carries book series information. However, the ASIN won't match for the individual parts of a multi-part book. An alternative option might be the SKU field which appears to be the same, complemented with a letter suffix for each part. 

You would don't know how many titles there are in the series. You could click the "View series" in the Audible App, which will download another JSON file with more info, but that would only reflect the current state as the series could be an ongoing one.

So the only solution for alphanumeric sorting with the sequence number would be a manual setting for the number of expected titles in a series: 10, 100, 1000. From that setting the zero-padding can be derived.

`Great Author/Great Series/06 - Sixth Title in the Series`

I will put it on the todo list.
