### ISSUE TITLE
Automatic Activation is not working

### ISSUE THREAD

**Issue by synystersparx** [audiamus/AaxAudioConverter#63]
Hi, this seems like a great free app! I'm unable to use it at the moment, however. The only app I saw for download on PC was "AudibleSync." I downloaded it and logged in, can see and download my audio books, but the AAX Audio Converter still has the "Audible activation code" popup, meaning it hasn't found the activation code automatically. 

What should I do? I have tried restarting both programs.

**Comment by synystersparx** [comment]
Apologies. Audible Sync wasn't the right program, but it was all I could find on the Audible website. I was able to find the correct app in the Microsoft Store and got it installed and it all seems to be working great.

**Comment by timur-tabi** [comment]
Please update the README to indicate that the app should be downloaded from the Microsoft Store.
