### ISSUE TITLE
Unable to activate or get activation code

### ISSUE THREAD

**Issue by Pentazer** [audiamus/AaxAudioConverter#64]
My account is through audible.ca not audible.com. The audible software only works with audible.com which doesn't have any of my purchases (it's an empty account). How do I get my activation code without using the audible app since the account on .com is a dud?

**Comment by phtnk** [comment]
Just happened to stumble upon this... The audible software - I guess you're talking about the app from the windows store - works with all regions, although I was confused at first, too. When you start the app - not being signed in - you'll see 'Marketplace: ...' below the Sign in button. Click on that, choose your location. Canada is amongst them.
It's a rather questionable design choice, but that's the case for the whole app, so no surprise.

**Comment by Pentazer** [comment]
Oh, wow that's bloody madness, but you are absolutely correct and that solved the problem perfectly. 
Thank you so much!
