### ISSUE TITLE
Sort by size is in character order instead of numerical

### ISSUE THREAD

**Issue by ikarusnc** [audiamus/AaxAudioConverter#7]
If you try to sort books by size 100 is before 200 but also 20 or 2.

**Comment by audiamus** [comment]
You have to explain to me in more detail what you are trying to achieve.

AAX Audio Converter uses default alphabetical sorting wherever order of items plays a role. When sorting tracks or chapters by number it will apply as many digits as needed to ensure correct order. A book with 99 tracks, for instance, will start with track 01, a book with 199 tracks will start with track 001.

**Comment by audiamus** [comment]
I can confirm this observation. The fix will be easy and done for the next version. The column sorter already supports order by a backing tag, so that will have to be set with the numeric value.

**Comment by audiamus** [comment]
Fixed in version 1.7.
