### ISSUE TITLE
Podcasts not correctly sorted

### ISSUE THREAD

**Issue by finnBsch** [audiamus/AaxAudioConverter#71]
I have an issue:
when downloading podcasts in audible, the files get saved as "Episode 1 - ...", "Episode 2 - ...", and so on. The title of the podcast itself is lost somehow which leads to issues when downloading multiple podcast from the same person. Anything I can do?

**Comment by audiamus** [comment]
I haven't analyzed podcast titles as I don't have any.  

What might work is to (mis-)use the multi-part book title parsing feature. You can try to add the word "episode" in the Basic Settings, Conversion tab, "custom search words for part". But I won't guarantee success. If it does work, it will treat each episode as a part of a multi-part book. This may have side effects, though. If you convert a couple of episodes, consecutively numbered and starting with 1, they will all be combined into a single playlist in one common folder.

If the automatic (i.e. heuristic) part/episode recognition fails or you don't like the outcome you should still be able to set the title manually, via the context menu for the book/podcast and the preview / customize dialog.

If you want me to have a closer look, run AAX Audio Converter with logging on, log level 3, and upload the log file (zipped). But see the manual for privacy hints first.

**Comment by finnBsch** [comment]
I think I was expressing myself a bit wrong. What I want is the converter to detect the Podcast name (not episode name)..

**Comment by audiamus** [comment]
It all depends on what the title says that is embedded as meta data in the AAX file.

**Comment by finnBsch** [comment]
okay, anyway I can influence that from within Audible? Could it be that they left that out?
One example:
Deep Sleep by Oliver Wunderlich, has 2 seasons, each 30 episodes
-> 2x Episode 1 by Oliver Wunderlich (because the information about the name of the podcast (Deep Sleep 1, Deep Sleep 2)) is lost -> issue

**Comment by audiamus** [comment]
I don't think you can. 

To say something helpful I really need the title of such an episode, as embedded in the AAX file. Either via the log option or with FFmpeg invoked directly.

**Comment by audiamus** [comment]
I'm closing this for the moment.

Please reopen when you can provide the full title from the AAX file.
