### ISSUE TITLE
1.17: app not starting

### ISSUE THREAD

**Issue by torxt** [audiamus/AaxAudioConverter#75]
Hello!
I'm trying the program for the first time, but it will not run on my system, it won't start.  

using app version 1.16 works

System: 
Windows 10 64bit pro 
app version 1.17

On my system is the following .NET Framework installed via https://github.com/EliteLoser/DotNetVersionLister
>=4.x        : 4.8 or later
v4\Client    : Installed
v4\Full      : Installed
v3.5         : Installed
v3.0         : Installed
v2.0.50727   : Installed
v1.1.4322    : Not installed (no key)

Error via windows event log:

Application: AaxAudioConverter.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
[....]
and 
Faulting application name: AaxAudioConverter.exe, version: 1.17.0.0, time stamp: 0xf595ea76
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
[..]

I'm running net 4.8 but cannot downgrade to 4.7, the runtime installer won't allow that. 
I tried to install .NET Framework 4.7.2 Developer Pack Offline Installer, which could be installed but the app is not starting and the dev pack is not showing up in the installed runtime.

does the build target needs to be pushed to 4.8 or is there anything i can do on my system? 

Thanks

**Comment by audiamus** [comment]
I don't think it's the .Net framework. 4.7.1 is the minimum version. Almost every Win 10 system will have 4.8.* installed.
 
To say more I would need the full exception call stack.

**Comment by UltimateLaForsch** [comment]
Ausnahmeinformationen: System.NullReferenceException
   bei audiamus.aaxconv.MainForm.listViewAaxFiles_SizeChanged(System.Object, System.EventArgs)
   bei System.Windows.Forms.Control.OnSizeChanged(System.EventArgs)
   bei System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32, Int32, Int32)
   bei System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32)
   bei System.Windows.Forms.Control.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   bei System.Windows.Forms.Control.ScaleControl(System.Drawing.SizeF, System.Windows.Forms.BoundsSpecified)
   bei System.Windows.Forms.Control.ScaleControl(System.Drawing.SizeF, System.Drawing.SizeF, System.Windows.Forms.Control)
   bei System.Windows.Forms.Control.Scale(System.Drawing.SizeF, System.Drawing.SizeF, System.Windows.Forms.Control)
   bei System.Windows.Forms.Control.ScaleChildControls(System.Drawing.SizeF, System.Drawing.SizeF, System.Windows.Forms.Control, Boolean)
   bei System.Windows.Forms.Control.Scale(System.Drawing.SizeF, System.Drawing.SizeF, System.Windows.Forms.Control)
   bei System.Windows.Forms.ContainerControl.OnChildLayoutResuming(System.Windows.Forms.Control, Boolean)
   bei System.Windows.Forms.Control.OnLayoutResuming(Boolean)
   bei System.Windows.Forms.Control.ResumeLayout(Boolean)
   bei audiamus.aaxconv.MainForm.InitializeComponent()
   bei audiamus.aaxconv.MainForm..ctor()
   bei audiamus.aaxconv.Program.Main(System.String[])

**Comment by audiamus** [comment]
Excellent, thank you both. I think I've found it.

**Comment by audiamus** [comment]
Should be fixed now, in 1.17.0.1

**Comment by UltimateLaForsch** [comment]
yep, it works now. many thx
