### ISSUE TITLE
Book title is cutted after "-"

### ISSUE THREAD

**Issue by ikarusnc** [audiamus/AaxAudioConverter#8]
Example: if the title is "Mage - a very lame fantasy" after the conversion, if you don't customize by hand, the filename and title become "Mage", changing naming option doens't solve the problem.

**Comment by audiamus** [comment]
Title parsing is based on a number of rules, but the rules originate from heuristic findings so they have their limitations. However, the preview/customization dialog - via context menu - will allow you to tweak the resulting title/author tag and file names to your liking.
