### ISSUE TITLE
tooltip pop-up is misattributed

### ISSUE THREAD

**Issue by ConsciousClay** [audiamus/AaxAudioConverter#81]
![image](https://user-images.githubusercontent.com/51193876/126077557-38ad3d56-3341-47bc-b095-d095ef3eb197.png)

The tooltip in the picture appears after hovering over **Full caption for book folder**.

This happened to me the first time I ran the app. After restarting the app, the tooltip appeared correctly. But after running the app a third time, the tooltip was misattributed again.

**Comment by audiamus** [comment]
Thank you for reporting this. Obviously a copy/paste error. The erroneous and redundant tooltip is indeed associated with the label **Full caption for book folder** and not with the checkbox which has the correct one.

**Comment by ConsciousClay** [comment]
Obvious to a programmer. Not so obvious to others. 😜
