### ISSUE TITLE
Cover Images & Extra File Gone

### ISSUE THREAD

**Issue by emaech** [audiamus/AaxAudioConverter#91]
I've just backed up my 5 most recent purchases and only got the m4a output. The setting is checked, and I haven't changed anything since I first installed it.

![image](https://user-images.githubusercontent.com/90889918/133731773-1f71115b-8f96-4a7b-a4b2-1e0236777934.png)

**Comment by audiamus** [comment]
Can you create and upload a log file for this case (log level 3)?

**Comment by emaech** [comment]
Nevermind... Avast Antivirus ransomware shield started "protecting" the output folder. It would let me create the folder and the m4a file, but then block additional changes, like adding the cover and the text file. Sorry for the waste of time :)
