### ISSUE TITLE
mp4 support?

### ISSUE THREAD

**Issue by leokleingmx** [audiamus/AaxAudioConverter#93]
Hi,

at least my audible is only offering .mp4 downloads now. I cannot open them with the tool, so I wonder if it is possible to add the support form them as well..

Best Regards,
leo

**Comment by leokleingmx** [comment]
ah... I had to rename them to .aax   !
So for me this is closed, but maybe add .mp4 to the list of files to open?!

**Comment by audiamus** [comment]
Well, basically .aax was always .mp4, albeit with an encrypted AAC audio stream. Don't know why Audible decided to confuse users with .mp4, as the files are still encrypted. 

I add it to the wish list. It will require additional file content checking to ensure it's really an Audible file.

_BTW: The Audible .aaxc files you would download on smartphones are also mp4 files, but the encryption is significantly more advanced there._
